[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = "$title.str(max_w:50)"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 30.0
alert = 20.0
format = " $icon / $available.eng(w:2) "

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total($mem_used_percents)"
format_alt = "$icon_swap $swap_used/$swap_total($swap_used_percents)"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"

[[block]]
block = "temperature"
interval = 10
format = "$icon $min min, $max max, $average avg"
format_alt = " $icon "
chip = "*-pci-*"

[[block]]
block = "net"
device = "enp38s0"
format = "$icon $ip $graph_down $speed_down $graph_up $speed_up"
interval = 5

[[block]]
block = "load"
interval = 1

[[block]]
block = "hueshift"
step = 50

[[block]]
block = "time"

[[block]]
block = "sound"
