theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 30.0
alert = 20.0

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min} min, {max} max, {average} avg"
chip = "*-pci-*"

[[block]]
block = "net"
device = "enp38s0"
format = "{ip} {speed_up;K*b} {graph_up;K*b} {speed_down;K*b} {graph_down;K*b}"
interval = 5

[[block]]
block = "load"
format = "{1m}"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
