# acyclic
# Autogenerated from man page /usr/local/share/man/man1/acyclic.1
# using Deroffing man parser
complete -c acyclic -s n --description 'No output is produced, though the return value … [See Man Page]'
complete -c acyclic -s v --description 'Print information about whether the file is acy… [See Man Page]'
complete -c acyclic -s o --description 'causes the output to be written to the specifie… [See Man Page]'
complete -c acyclic -s '?' --description 'option causes the program to print usage information.'

