# amlint
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/amlint.1
# using Darwin man parser
complete -c amlint -s H --description 'Print the filename for each error or warning.'
complete -c amlint -s h --description 'Suppress the prefixing of filenames when multip… [See Man Page]'
complete -c amlint -s S --description 'For each action, write a summary line indicatin… [See Man Page]'
complete -c amlint -s s --description 'As S, but skips the summary line for actions wi… [See Man Page]'
complete -c amlint -s d --description 'Specify a definition bundle, which specifies cu… [See Man Page]'
complete -c amlint -s x --description 'Specify a list of errors and warnings to ignore.'

