# ar
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/ar.1
# using Darwin man parser
complete -c ar -s a --description 'A positioning modifier used with the options r and m.'
complete -c ar -s b --description 'A positioning modifier used with the options r and m.'
complete -c ar -s c --description 'Whenever an archive is created, an informationa… [See Man Page]'
complete -c ar -s d --description 'Delete the specified archive files.'
complete -c ar -s i --description 'Identical to the b option.'
complete -c ar -s m --description 'Move the specified archive files within the archive.'
complete -c ar -s o --description 'Set the access and modification times of extrac… [See Man Page]'
complete -c ar -s p --description 'Write the contents of the specified archive fil… [See Man Page]'
complete -c ar -s q --description '(Quickly) append the specified files to the archive.'
complete -c ar -s r --description 'Replace or add the specified files to the archive.'
complete -c ar -s T --description 'Select and/or name archive members using only t… [See Man Page]'
complete -c ar -s L --description 'Used the extended format to allow long archive member names.'
complete -c ar -s s --description 'Write an object-file index into the archive, or… [See Man Page]'
complete -c ar -s S --description 'Do not generate an archive symbol table.'
complete -c ar -s t --description 'List the specified files in the order in which … [See Man Page]'
complete -c ar -s u --description 'Update files.'
complete -c ar -s v --description 'Provide verbose output.'
complete -c ar -s x --description 'Extract the specified archive members into the … [See Man Page]'

