# as
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/as.1
# using Deroffing man parser
complete -c as -s o --description 'Name the output file  name instead of  a. out .'
complete -c as -o arch --description 'Specifies the target architecture, R arch_type … [See Man Page]'
complete -c as -o arch_multiple --description 'Precede any displayed messages with a line stat… [See Man Page]'
complete -c as -o force_cpusubtype_ALL --description 'By default, the assembler will produce the CPU … [See Man Page]'
complete -c as -o dynamic --description 'Enables dynamic linking features.  This is the default.'
complete -c as -o static --description 'Causes the assembler to treat as an error any f… [See Man Page]'
complete -c as -s '\\' --description 'Use   stdin  for the assembly source input.'
complete -c as -s n --description 'Instructs the assembler not to assume that the … [See Man Page]'
complete -c as -s f --description 'Fast; no need for the assembler preprocessor (``app\'\').'
complete -c as -s g --description 'Produce debugging information for the symbolic … [See Man Page]'
complete -c as -s v --description 'Display the version of the assembler (both the … [See Man Page]'
complete -c as -s V --description 'Print the path and the command line of the asse… [See Man Page]'
complete -c as -s I --description 'Add the directory  dir to the list of directori… [See Man Page]'
complete -c as -s W --description 'Suppress warnings.'
complete -c as -s L --description 'Save non-global defined labels beginning with a… [See Man Page]'
complete -c as -s q --description 'Use the R clang (1) integrated assembler instea… [See Man Page]'
complete -c as -s Q --description 'Use the GNU based system assembler.'
complete -c as -o static_branch_prediction_Y_bit --description 'Treat a single trailing \'+\' or \'-\' after a cond… [See Man Page]'
complete -c as -o static_branch_prediction_AT_bits --description 'Treat a single trailing \'+\' or \'-\' after a cond… [See Man Page]'
complete -c as -o no_ppc601 --description 'Treat any PowerPC 601 instructions as an error.  FILES a.'

