# asn1Decoding
# Autogenerated from man page /usr/local/share/man/man1/asn1Decoding.1
# using Deroffing man parser
complete -c asn1Decoding -s b -l benchmark --description 'perform a benchmark on decoding.'
complete -c asn1Decoding -s s -l strict --description 'use strict DER decoding.'
complete -c asn1Decoding -s h -l help --description 'display this help and exit.'
complete -c asn1Decoding -s v -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

