# aspcud
# Autogenerated from man page /usr/local/share/man/man1/aspcud.1
# using Deroffing man parser
complete -c aspcud -s h -l help --description 'print help text, and default configurations and paths.'
complete -c aspcud -s v -l version --description 'print version and license information.'
complete -c aspcud -s c --description 'append clasp option OPT (can be given multiple … [See Man Page]'
complete -c aspcud -s e --description 'append encoding ENC (can be given multiple time… [See Man Page]'
complete -c aspcud -s p --description 'append cudf2lp option OPT (can be given multiple times).'
complete -c aspcud -s s --description 'path to solver (clasp).'
complete -c aspcud -s g --description 'path to grounder (gringo).'
complete -c aspcud -s l --description 'path to cudf preprocessor (cudf2lp).'
complete -c aspcud -s d --description 'print debug info and do not cleanup temporary files.'

