# bitcode_strip
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/bitcode_strip.1
# using Deroffing man parser
complete -c bitcode_strip -s o --description 'specifies the output file as  output.'
complete -c bitcode_strip -s r --description 'specifies the bitcode segment is to be removed.'
complete -c bitcode_strip -s m --description 'specifies the bitcode segment is to be removed … [See Man Page]'
complete -c bitcode_strip -s l --description 'specifies that only the bitcode segment is to b… [See Man Page]'

