# brew
# Autogenerated from man page /usr/local/share/man/man1/brew.1
# using Deroffing man parser
complete -c brew -l cache --description 'Display Homebrew\'s download cache.  See also HOMEBREW_CACHE.'
complete -c brew -l cellar --description 'Display Homebrew\'s Cellar path.'
complete -c brew -l env --description 'Show a summary of the Homebrew build environment.'
complete -c brew -l prefix --description 'Display Homebrew\'s install path.  Default: /usr/local.'
complete -c brew -l repository --description 'Display where Homebrew\'s . git directory is located.'
complete -c brew -l version --description 'Print the version number of brew to standard error and exit.'

