# brew-cask
# Autogenerated from man page /usr/local/share/man/man1/brew-cask.1
# using Type1
complete -c brew-cask -l force --description 'Force an install to proceed even when a previou… [See Man Page]'
complete -c brew-cask -l caskroom --description 'Location of the Caskroom, where all binaries are stored.'
complete -c brew-cask -l verbose --description 'Give additional feedback during installation.'
complete -c brew-cask -l appdir --description 'Target location for Application links.'
complete -c brew-cask -l colorpickerdir --description 'Target location for Color Picker links.'
complete -c brew-cask -l prefpanedir --description 'Target location for Preference Pane links.'
complete -c brew-cask -l qlplugindir --description 'Target location for QuickLook Plugin links.'
complete -c brew-cask -l fontdir --description 'Target location for Font links.'
complete -c brew-cask -l servicedir --description 'Target location for Service links.'
complete -c brew-cask -l input_methoddir --description 'Target location for Input Method links.'
complete -c brew-cask -l internet_plugindir --description 'Target location for Internet Plugin links.'
complete -c brew-cask -l audio_unit_plugindir --description 'Target location for Audio Unit Plugin links.'
complete -c brew-cask -l vst_plugindir --description 'Target location for VST Plugin links.'
complete -c brew-cask -l screen_saverdir --description 'Target location for Screen Saver links.'
complete -c brew-cask -l no-binaries --description 'Do not link "helper" executables to /usr/local/bin.'
complete -c brew-cask -l binarydir --description 'Target location for "helper" executable links.'

