# broadwayd
# Autogenerated from man page /usr/local/share/man/man1/broadwayd.1
# using Deroffing man parser
complete -c broadwayd -l port --description 'Use PORT as the HTTP port, instead of the defau… [See Man Page]'
complete -c broadwayd -l address --description 'Use ADDRESS as the HTTP address, instead of the… [See Man Page]'
complete -c broadwayd -l unixsocket --description 'Use ADDRESS as the unix domain socket address.'
complete -c broadwayd -l 'port.' --description '.'

