# BuildStrings
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/BuildStrings.1
# using Darwin man parser
complete -c BuildStrings -o header --description 'Generate a header file.'
complete -c BuildStrings -o define --description 'Defines variable for use in #ifdef or #ifndef conditionals.'
complete -c BuildStrings -o id --description 'The resource ID for the STR# resource.'
complete -c BuildStrings -o attributes --description 'Resource attributes for the STR# resource defin… [See Man Page]'
complete -c BuildStrings -o type --description 'Customizes three preprocessor variables (MinVal… [See Man Page]'
complete -c BuildStrings -o in --description 'The input file, a set of newline-separated pair… [See Man Page]'
complete -c BuildStrings -o out --description 'The output file.'

