# c89
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/c89.1
# using Darwin man parser
complete -c c89 -s c --description 'Suppress the link-edit phase of the compilation… [See Man Page]'
complete -c c89 -s D --description 'Define name as if by a C-language #define directive.'
complete -c c89 -s E --description 'Copy C-language source files to the standard ou… [See Man Page]'
complete -c c89 -s g --description 'Produce symbolic information in the object or executable files.'
complete -c c89 -s I --description 'Change the algorithm for searching for headers … [See Man Page]'
complete -c c89 -s L --description 'Change the algorithm of searching for the libra… [See Man Page]'
complete -c c89 -s o --description 'Use the pathname outfile, instead of the default a.'
complete -c c89 -s O --description 'If optlevel is zero, disable all optimizations.'
complete -c c89 -s s --description 'Produce object and/or executable files from whi… [See Man Page]'
complete -c c89 -s U --description 'Remove any initial definition of name.'
complete -c c89 -s W --description 'Set the pointer size for the compiled code to e… [See Man Page]'
complete -c c89 -s l --description 'Search the library named lib Ns Ar library Ns Pa . a.'

