# cargo
# Autogenerated from man page /usr/local/share/man/man1/cargo.1
# using Deroffing man parser
complete -c cargo -s h -l help --description 'Display a help message.'
complete -c cargo -s V -l version --description 'Print version information and exit.'
complete -c cargo -l list --description 'List all available cargo commands.'
complete -c cargo -s v -l verbose --description 'Use verbose output.'
complete -c cargo -l color --description 'Configure coloring of output.'

