# clusterdb
# Autogenerated from man page /usr/local/share/man/man1/clusterdb.1
# using Deroffing man parser
complete -c clusterdb -o 'a
.br
--all' --description 'Cluster all databases.'
complete -c clusterdb -o 'e
.br
--echo' --description 'Echo the commands that clusterdb generates and … [See Man Page]'
complete -c clusterdb -o 'q
.br
--quiet' --description 'Do not display progress messages.'
complete -c clusterdb -s t --description 'Cluster table only.'
complete -c clusterdb -o 'v
.br
--verbose' --description 'Print detailed information during processing.'
complete -c clusterdb -o 'V
.br
--version' --description 'Print the clusterdb version and exit.'
complete -c clusterdb -o '?
.br
--help' --description 'Show help about clusterdb command line arguments, and exit.'
complete -c clusterdb -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c clusterdb -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c clusterdb -s U --description 'User name to connect as.'
complete -c clusterdb -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c clusterdb -o 'W
.br
--password' --description 'Force clusterdb to prompt for a password before… [See Man Page]'
complete -c clusterdb -l maintenance-db --description 'Specifies the name of the database to connect t… [See Man Page]'
complete -c clusterdb -s a --description '.'
complete -c clusterdb -l all --description '.'
complete -c clusterdb -l 'all)' --description 'PGDATABASE.'
complete -c clusterdb -s e --description '.'
complete -c clusterdb -l echo --description '.'
complete -c clusterdb -s q --description '.'
complete -c clusterdb -l quiet --description '.'
complete -c clusterdb -l table --description '.'
complete -c clusterdb -s v --description '.'
complete -c clusterdb -l verbose --description '.'
complete -c clusterdb -s V --description '.'
complete -c clusterdb -l version --description '.'
complete -c clusterdb -s '?' --description '.'
complete -c clusterdb -l help --description '.'
complete -c clusterdb -l host --description '.'
complete -c clusterdb -l port --description '.'
complete -c clusterdb -l username --description '.'
complete -c clusterdb -s w --description '.'
complete -c clusterdb -l no-password --description '.'
complete -c clusterdb -s W --description '.'
complete -c clusterdb -l password --description '.'

