# cluster
# Autogenerated from man page /usr/local/share/man/man1/cluster.1
# using Deroffing man parser
complete -c cluster -s C --description 'specifies a targeted number of clusters that sh… [See Man Page]'
complete -c cluster -s c --description 'specifies clustering method.'
complete -c cluster -s o --description 'Specifies that output should go into the file outfile.'
complete -c cluster -s v --description 'Verbose mode.  EXAMPLES.'

