# codesign_allocate
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/codesign_allocate.1
# using Deroffing man parser
complete -c codesign_allocate -s i --description 'specifies the input file as  oldfile.'
complete -c codesign_allocate -s o --description 'specifies the output file as  newfile.'
complete -c codesign_allocate -s a --description 'specifies for the architecture  arch that the s… [See Man Page]'

