# CpMac
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/CpMac.1
# using Darwin man parser
complete -c CpMac -s r --description 'If source designates a directory, CpMac copies … [See Man Page]'
complete -c CpMac -s p --description 'Causes CpMac to preserve in the copy as many of… [See Man Page]'
complete -c CpMac -o mac --description 'Allows use of HFS-style paths for both source and target.'

