# createlang
# Autogenerated from man page /usr/local/share/man/man1/createlang.1
# using Deroffing man parser
complete -c createlang -o 'e
.br
--echo' --description 'Display SQL commands as they are executed.'
complete -c createlang -o 'l
.br
--list' --description 'Show a list of already installed languages in t… [See Man Page]'
complete -c createlang -o 'V
.br
--version' --description 'Print the createlang version and exit.'
complete -c createlang -o '?
.br
--help' --description 'Show help about createlang command line arguments, and exit.'
complete -c createlang -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c createlang -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c createlang -s U --description 'User name to connect as.'
complete -c createlang -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c createlang -o 'W
.br
--password' --description 'Force createlang to prompt for a password befor… [See Man Page]'
complete -c createlang -s e --description '.'
complete -c createlang -l echo --description '.'
complete -c createlang -s l --description '.'
complete -c createlang -l list --description '.'
complete -c createlang -s V --description '.'
complete -c createlang -l version --description '.'
complete -c createlang -s '?' --description '.'
complete -c createlang -l help --description '.'
complete -c createlang -l host --description '.'
complete -c createlang -l port --description '.'
complete -c createlang -l username --description '.'
complete -c createlang -s w --description '.'
complete -c createlang -l no-password --description '.'
complete -c createlang -s W --description '.'
complete -c createlang -l password --description '.'

