# createuser
# Autogenerated from man page /usr/local/share/man/man1/createuser.1
# using Deroffing man parser
complete -c createuser -s c --description 'Set a maximum number of connections for the new user.'
complete -c createuser -o 'd
.br
--createdb' --description 'The new user will be allowed to create databases.'
complete -c createuser -o 'D
.br
--no-createdb' --description 'The new user will not be allowed to create databases.'
complete -c createuser -o 'e
.br
--echo' --description 'Echo the commands that createuser generates and… [See Man Page]'
complete -c createuser -o 'E
.br
--encrypted' --description 'Encrypts the user\\*(Aqs password stored in the database.'
complete -c createuser -s g --description 'Indicates role to which this role will be added… [See Man Page]'
complete -c createuser -o 'i
.br
--inherit' --description 'The new role will automatically inherit privile… [See Man Page]'
complete -c createuser -o 'I
.br
--no-inherit' --description 'The new role will not automatically inherit pri… [See Man Page]'
complete -c createuser -l interactive --description 'Prompt for the user name if none is specified o… [See Man Page]'
complete -c createuser -o 'l
.br
--login' --description 'The new user will be allowed to log in (that is… [See Man Page]'
complete -c createuser -o 'L
.br
--no-login' --description 'The new user will not be allowed to log in.'
complete -c createuser -o 'N
.br
--unencrypted' --description 'Does not encrypt the user\\*(Aqs password stored… [See Man Page]'
complete -c createuser -o 'P
.br
--pwprompt' --description 'If given, createuser will issue a prompt for th… [See Man Page]'
complete -c createuser -o 'r
.br
--createrole' --description 'The new user will be allowed to create new role… [See Man Page]'
complete -c createuser -o 'R
.br
--no-createrole' --description 'The new user will not be allowed to create new roles.'
complete -c createuser -o 's
.br
--superuser' --description 'The new user will be a superuser.'
complete -c createuser -o 'S
.br
--no-superuser' --description 'The new user will not be a superuser.  This is the default.'
complete -c createuser -o 'V
.br
--version' --description 'Print the createuser version and exit.'
complete -c createuser -l replication --description 'The new user will have the REPLICATION privileg… [See Man Page]'
complete -c createuser -l no-replication --description 'The new user will not have the REPLICATION priv… [See Man Page]'
complete -c createuser -o '?
.br
--help' --description 'Show help about createuser command line arguments, and exit.'
complete -c createuser -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c createuser -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c createuser -s U --description 'User name to connect as (not the user name to create).'
complete -c createuser -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c createuser -o 'W
.br
--password' --description 'Force createuser to prompt for a password (for … [See Man Page]'
complete -c createuser -l connection-limit --description '.'
complete -c createuser -s d --description '.'
complete -c createuser -l createdb --description '.'
complete -c createuser -s D --description '.'
complete -c createuser -l no-createdb --description '.'
complete -c createuser -s e --description '.'
complete -c createuser -l echo --description '.'
complete -c createuser -s E --description '.'
complete -c createuser -l encrypted --description '.'
complete -c createuser -l role --description '.'
complete -c createuser -s i --description '.'
complete -c createuser -l inherit --description '.'
complete -c createuser -s I --description '.'
complete -c createuser -l no-inherit --description '.'
complete -c createuser -o d/-D --description '.'
complete -c createuser -o r/-R --description '.'
complete -c createuser -o s/-S --description 'is not specified on the command line.'
complete -c createuser -s l --description '.'
complete -c createuser -l login --description '.'
complete -c createuser -s L --description '.'
complete -c createuser -l no-login --description '.'
complete -c createuser -s N --description '.'
complete -c createuser -l unencrypted --description '.'
complete -c createuser -s P --description '.'
complete -c createuser -l pwprompt --description '.'
complete -c createuser -s r --description '.'
complete -c createuser -l createrole --description '.'
complete -c createuser -s R --description '.'
complete -c createuser -l no-createrole --description '.'
complete -c createuser -s s --description '.'
complete -c createuser -l superuser --description '.'
complete -c createuser -s S --description '.'
complete -c createuser -l no-superuser --description '.'
complete -c createuser -s V --description '.'
complete -c createuser -l version --description '.'
complete -c createuser -s '?' --description '.'
complete -c createuser -l help --description '.'
complete -c createuser -l host --description '.'
complete -c createuser -l port --description '.'
complete -c createuser -l username --description '.'
complete -c createuser -s w --description '.'
complete -c createuser -l no-password --description '.'
complete -c createuser -s W --description '.'
complete -c createuser -l password --description '.'

