# ctags
# Autogenerated from man page /usr/local/share/man/man1/ctags.1
# using Deroffing man parser
complete -c ctags -l list-maps -l langmap --description 'On platforms which support it, if the name of a… [See Man Page]'
complete -c ctags -s e --description 'Enable etags mode, which will create a tag file… [See Man Page]'
complete -c ctags -s h --description 'Specifies a list of file extensions, separated … [See Man Page]'
complete -c ctags -s I --description 'Specifies a list of identifiers which are to be… [See Man Page]'
complete -c ctags -s L --description 'Read from file a list of file names for which t… [See Man Page]'
complete -c ctags -s n --description 'Equivalent to --excmd=number.'
complete -c ctags -s N --description 'Equivalent to --excmd=pattern.'
complete -c ctags -s o --description 'Equivalent to -f tagfile.'
complete -c ctags -s R --description 'Equivalent to --recurse.'
complete -c ctags -s V --description 'Equivalent to --verbose.'
complete -c ctags -l file-scope --description 'file name.'
complete -c ctags -l 'append[' --description 'Indicates whether tags generated from the speci… [See Man Page]'
complete -c ctags -l etags-include --description 'Include a reference to file in the tag file.'
complete -c ctags -l exclude --description 'Add pattern to a list of excluded files and directories.'
complete -c ctags -l version --description 'feature list; otherwise, pattern is matched aga… [See Man Page]'
complete -c ctags -l excmd --description 'Determines the type of EX command used to locat… [See Man Page]'

