# cudf2lp
# Autogenerated from man page /usr/local/share/man/man1/cudf2lp.1
# using Deroffing man parser
complete -c cudf2lp -s h -l help --description 'print help text.'
complete -c cudf2lp -s v -l version --description 'print version and license information.'
complete -c cudf2lp -s V -l 'verbose[' --description 'set the verbosity level to N or the maximum if omitted.'
complete -c cudf2lp -s c -l criteria --description 'preprocess for specific optimization criteria (… [See Man Page]'
complete -c cudf2lp -l addall --description 'disable preprocessing and add all packages.'

