# DeRez
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/DeRez.1
# using Deroffing man parser
complete -c DeRez -o 'c[ompatible]' --description 'Generates output that is backward-compatible with   Rez  1. 0.'
complete -c DeRez -o 'd[efine]' --description 'Defines the macro variable   macro  as having the value   data.'
complete -c DeRez -o 'e[scape]' --description 'Prints characters that are normally escaped, su… [See Man Page]'
complete -c DeRez -s i --description 'Specifies the directory to search for   #include  files.'
complete -c DeRez -o 'is[ysroot]' --description 'Specifies the system SDK in which to search for… [See Man Page]'
complete -c DeRez -o 'm[axstringsize]' --description 'Sets the maximum output string width to   n,  w… [See Man Page]'
complete -c DeRez -o noResolve --description 'Suppresses leaf alias resolution of the file or… [See Man Page]'
complete -c DeRez -o only --description 'Reads only resources of the type indicated by   typeExpr.'
complete -c DeRez -s p --description 'Writes progress and summary information to standard output.'
complete -c DeRez -o rd --description 'Suppresses warning messages emitted when a reso… [See Man Page]'
complete -c DeRez -o script --description 'Enables the recognition of any of several 2-byt… [See Man Page]'
complete -c DeRez -o 's[kip]' --description 'Skips resources of the type indicated by   typeExpr.'
complete -c DeRez -o skip --description 'br -skip -only "\'MENU\' ("\'"Edit"\'")".'
complete -c DeRez -o 'u[ndef]' --description 'Undefines the preset macro variable  macro.'
complete -c DeRez -o useDF --description 'Reads and writes resource information from the … [See Man Page]'

