# docsetutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/docsetutil.1
# using Darwin man parser
complete -c docsetutil -o localization --description 'Perform the operation using a particular locali… [See Man Page]'
complete -c docsetutil -o skip-text --description 'Do not perform the operation for the full-text index.'
complete -c docsetutil -o skip-api --description 'Do not perform the operation for the API index.'
complete -c docsetutil -o node --description 'Perform the operation only on the documents tha… [See Man Page]'
complete -c docsetutil -o verbose --description 'Print out additional information about the oper… [See Man Page]'
complete -c docsetutil -o debug --description 'Print out detailed information about the operat… [See Man Page]'
complete -c docsetutil -o fallback --description 'Documentation sets can distribute their content… [See Man Page]'
complete -c docsetutil -o download --description 'If a node uses an absolute URL for its landing … [See Man Page]'
complete -c docsetutil -o query --description 'The string to search for in both the full-text and API index.'
complete -c docsetutil -o text-tree --description 'When set, the text search results are presented… [See Man Page]'
complete -c docsetutil -o toc-depth --description 'When printing out the table-of-content hierarch… [See Man Page]'
complete -c docsetutil -o text-depth --description 'When printing the files from the full-text inde… [See Man Page]'
complete -c docsetutil -o output --description 'The path of the archive to create.'
complete -c docsetutil -o signid --description 'Include a digital signature in the archive usin… [See Man Page]'
complete -c docsetutil -o atom --description 'Generate or update an entry about the documenta… [See Man Page]'
complete -c docsetutil -o download-url --description 'Use the given URL as the download location of t… [See Man Page]'

