# droplang
# Autogenerated from man page /usr/local/share/man/man1/droplang.1
# using Deroffing man parser
complete -c droplang -o 'e
.br
--echo' --description 'Display SQL commands as they are executed.'
complete -c droplang -o 'l
.br
--list' --description 'Show a list of already installed languages in t… [See Man Page]'
complete -c droplang -o 'V
.br
--version' --description 'Print the droplang version and exit.'
complete -c droplang -o '?
.br
--help' --description 'Show help about droplang command line arguments, and exit.'
complete -c droplang -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c droplang -s p --description 'Specifies the Internet TCP/IP port or local Uni… [See Man Page]'
complete -c droplang -s U --description 'User name to connect as.'
complete -c droplang -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c droplang -o 'W
.br
--password' --description 'Force droplang to prompt for a password before … [See Man Page]'
complete -c droplang -s e --description '.'
complete -c droplang -l echo --description '.'
complete -c droplang -s l --description '.'
complete -c droplang -l list --description '.'
complete -c droplang -s V --description '.'
complete -c droplang -l version --description '.'
complete -c droplang -s '?' --description '.'
complete -c droplang -l help --description '.'
complete -c droplang -l host --description '.'
complete -c droplang -l port --description '.'
complete -c droplang -l username --description '.'
complete -c droplang -s w --description '.'
complete -c droplang -l no-password --description '.'
complete -c droplang -s W --description '.'
complete -c droplang -l password --description '.'

