# dropuser
# Autogenerated from man page /usr/local/share/man/man1/dropuser.1
# using Deroffing man parser
complete -c dropuser -o 'e
.br
--echo' --description 'Echo the commands that dropuser generates and s… [See Man Page]'
complete -c dropuser -o 'i
.br
--interactive' --description 'Prompt for confirmation before actually removin… [See Man Page]'
complete -c dropuser -o 'V
.br
--version' --description 'Print the dropuser version and exit.'
complete -c dropuser -l if-exists --description 'Do not throw an error if the user does not exist.'
complete -c dropuser -o '?
.br
--help' --description 'Show help about dropuser command line arguments, and exit.'
complete -c dropuser -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c dropuser -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c dropuser -s U --description 'User name to connect as (not the user name to drop).'
complete -c dropuser -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c dropuser -o 'W
.br
--password' --description 'Force dropuser to prompt for a password before … [See Man Page]'
complete -c dropuser -o i/--interactive --description 'option is used.'
complete -c dropuser -s e --description '.'
complete -c dropuser -l echo --description '.'
complete -c dropuser -s i --description '.'
complete -c dropuser -l interactive --description '.'
complete -c dropuser -s V --description '.'
complete -c dropuser -l version --description '.'
complete -c dropuser -s '?' --description '.'
complete -c dropuser -l help --description '.'
complete -c dropuser -l host --description '.'
complete -c dropuser -l port --description '.'
complete -c dropuser -l username --description '.'
complete -c dropuser -s w --description '.'
complete -c dropuser -l no-password --description '.'
complete -c dropuser -s W --description '.'
complete -c dropuser -l password --description '.'

