# DVTInstallationService
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/DVTInstallationService.1
# using Darwin man parser
complete -c DVTInstallationService -s a --description 'Description of -a flag.'
complete -c DVTInstallationService -s b --description 'Description of -b flag \\" Ends the list Pp .'

