# dyldinfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/dyldinfo.1
# using Darwin man parser
complete -c dyldinfo -o arch --description 'Only display the specified architecture.'
complete -c dyldinfo -o dylibs --description 'Display the table of dylibs on which this image depends.'
complete -c dyldinfo -o rebase --description 'Display the table of rebasing information.'
complete -c dyldinfo -o bind --description 'Display the table of binding information.'
complete -c dyldinfo -o weak_bind --description 'Display the table of weak binding information.'
complete -c dyldinfo -o lazy_bind --description 'Display the table of lazy binding information.'
complete -c dyldinfo -o export --description 'Display the table symbols which this image exports.'
complete -c dyldinfo -o opcodes --description 'Display the low level opcodes used to encode al… [See Man Page]'
complete -c dyldinfo -o function_starts --description 'Decodes the list of function start addresses.'

