# ecpg
# Autogenerated from man page /usr/local/share/man/man1/ecpg.1
# using Deroffing man parser
complete -c ecpg -s c --description 'Automatically generate certain C code from SQL code.'
complete -c ecpg -s C --description 'Set a compatibility mode.  mode can be INFORMIX or INFORMIX_SE.'
complete -c ecpg -s D --description 'Define a C preprocessor symbol.'
complete -c ecpg -s i --description 'Parse system include files as well.'
complete -c ecpg -s I --description 'Specify an additional include path, used to fin… [See Man Page]'
complete -c ecpg -s o --description 'Specifies that ecpg should write all its output… [See Man Page]'
complete -c ecpg -s t --description 'Turn on autocommit of transactions.'
complete -c ecpg -s v --description 'Print additional information including the vers… [See Man Page]'
complete -c ecpg -l version --description 'Print the ecpg version and exit.'
complete -c ecpg -o '?
.br
--help' --description 'Show help about ecpg command line arguments, and exit.'
complete -c ecpg -s r --description '.'
complete -c ecpg -s '?' --description '.'
complete -c ecpg -l help --description '.'
complete -c ecpg -o 'I/usr/local/pgsql/include).' --description '.'
complete -c ecpg -o L/usr/local/pgsql/lib -o 'lecpg.' --description '.'

