# fax2ps
# Autogenerated from man page /usr/local/share/man/man1/fax2ps.1
# using Deroffing man parser
complete -c fax2ps -s p --description 'Print only the indicated page.'
complete -c fax2ps -s x --description 'Use  resolution as the horizontal resolution, i… [See Man Page]'
complete -c fax2ps -s y --description 'Use  resolution as the vertical resolution, in … [See Man Page]'
complete -c fax2ps -s S --description 'Scale each page of image data to fill the outpu… [See Man Page]'
complete -c fax2ps -s W --description 'Use  width as the width, in inches, of the output page.'
complete -c fax2ps -s H --description 'options.'

