# g-ir-compiler
# Autogenerated from man page /usr/local/share/man/man1/g-ir-compiler.1
# using Deroffing man parser
complete -c g-ir-compiler -l -help --description 'Show help options.'
complete -c g-ir-compiler -l -output --description 'Save the resulting output in FILENAME.'
complete -c g-ir-compiler -l -verbose --description 'Show verbose messages.'
complete -c g-ir-compiler -l -debug --description 'Show debug messages.'
complete -c g-ir-compiler -l -includedir --description 'Adds a directory which will be used to find inc… [See Man Page]'
complete -c g-ir-compiler -l -module --description 'FIXME.'
complete -c g-ir-compiler -l -shared-library --description 'Specifies the shared library where the symbols … [See Man Page]'

