# gccmakedep
# Autogenerated from man page /opt/X11/share/man/man1/gccmakedep.1
# using Deroffing man parser
complete -c gccmakedep -s a --description 'Append the dependencies to the file instead of … [See Man Page]'
complete -c gccmakedep -s f --description 'Filename.'
complete -c gccmakedep -s s --description 'Starting string delimiter.'
complete -c gccmakedep -s D --description 'and.'
complete -c gccmakedep -s U --description 'options to define and undefine symbols and.'
complete -c gccmakedep -s I --description 'to set the include path.'
complete -c gccmakedep -o f- --description 'sends the output to standard output instead of … [See Man Page]'

