# gdk-pixbuf-csource
# Autogenerated from man page /usr/local/share/man/man1/gdk-pixbuf-csource.1
# using Deroffing man parser
complete -c gdk-pixbuf-csource -l stream --description 'Generate pixbuf data stream (a single string co… [See Man Page]'
complete -c gdk-pixbuf-csource -l struct --description 'Generate GdkPixdata structure (needs the GdkPix… [See Man Page]'
complete -c gdk-pixbuf-csource -l macros --description 'Generate *_ROWSTRIDE, *_WIDTH, *_HEIGHT, *_BYTE… [See Man Page]'
complete -c gdk-pixbuf-csource -l rle --description 'Enables run-length encoding for the generated p… [See Man Page]'
complete -c gdk-pixbuf-csource -l raw --description 'Disables run-length encoding for the generated pixel data.'
complete -c gdk-pixbuf-csource -l extern --description 'Generate extern symbols.'
complete -c gdk-pixbuf-csource -l static --description 'Generate static symbols (default).'
complete -c gdk-pixbuf-csource -l decoder --description 'Provide a *_RUN_LENGTH_DECODE(image_buf, rle_da… [See Man Page]'
complete -c gdk-pixbuf-csource -l name --description 'Specifies the identifier name (prefix) for the … [See Man Page]'
complete -c gdk-pixbuf-csource -l build-list --description 'Enables (name, image) pair parsing mode.'
complete -c gdk-pixbuf-csource -s h -l help --description 'Print brief help and exit.'
complete -c gdk-pixbuf-csource -s v -l version --description 'Print version and exit.'
complete -c gdk-pixbuf-csource -l g-fatal-warnings --description 'Make warnings fatal (causes the program to abort).'

