# gdk-pixbuf-query-loaders
# Autogenerated from man page /usr/local/share/man/man1/gdk-pixbuf-query-loaders.1
# using Deroffing man parser
complete -c gdk-pixbuf-query-loaders -l update-cache --description 'Write the output to the default cache location … [See Man Page]'

