# GetFileInfo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/GetFileInfo.1
# using Darwin man parser
complete -c GetFileInfo -s P --description 'Acts on a symlink file instead of the file the … [See Man Page]'
complete -c GetFileInfo -o 'a[<attribute-letter>]' --description 'Gets a file\'s attribute bits where <attribute-l… [See Man Page]'
complete -c GetFileInfo -s t --description 'Gets the file type, a string of exactly four characters.'
complete -c GetFileInfo -s c --description 'Gets the file\'s creator, a string of four chara… [See Man Page]'
complete -c GetFileInfo -s d --description 'Gets the creation date, a string of the form "m… [See Man Page]'
complete -c GetFileInfo -s m --description 'Gets the modification date, a string of the for… [See Man Page]'

