# git-for-each-ref
# Autogenerated from man page /usr/local/share/man/man1/git-for-each-ref.1
# using Deroffing man parser
complete -c git-for-each-ref -l points-at --description 'Only list refs which points at the given object.'
complete -c git-for-each-ref -l merged --description 'Only list refs whose tips are reachable from th… [See Man Page]'
complete -c git-for-each-ref -l no-merged --description 'Only list refs whose tips are not reachable fro… [See Man Page]'
complete -c git-for-each-ref -l contains --description 'Only list tags which contain the specified comm… [See Man Page]'
complete -c git-for-each-ref -l quote --description 'everything in between %(align:.'

