# git-grep
# Autogenerated from man page /usr/local/share/man/man1/git-grep.1
# using Deroffing man parser
complete -c git-grep -o 'O[<pager>]' -l 'open-files-in-pager[' --description 'Open the matching files in the pager (not the output of grep).'

