# git-send-email
# Autogenerated from man page /usr/local/share/man/man1/git-send-email.1
# using Deroffing man parser
complete -c git-send-email -l dump-aliases --description 'Instead of the normal operation, dump the short… [See Man Page]'

