# git-worktree
# Autogenerated from man page /usr/local/share/man/man1/git-worktree.1
# using Deroffing man parser
complete -c git-worktree -l porcelain --description 'With list, output in an easy-to-parse format for scripts.'

