# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -l follow --description 'option was used when a single <path> is given.'
complete -c git-config -l recurse-submodules --description 'rebase. stat.'

