# git-branch
# Autogenerated from man page /usr/local/share/man/man1/git-branch.1
# using Deroffing man parser
complete -c git-branch -l sort --description 'Sort based on the key given.'
complete -c git-branch -l points-at --description 'Only list branches of the given object.'

