# git-checkout
# Autogenerated from man page /usr/local/share/man/man1/git-checkout.1
# using Deroffing man parser
complete -c git-checkout -l '[no-]progress' --description 'Progress status is reported on the standard err… [See Man Page]'
complete -c git-checkout -l 'quiet.' --description '.'

