# git-push
# Autogenerated from man page /usr/local/share/man/man1/git-push.1
# using Deroffing man parser
complete -c git-push -l no-recurse-submodules --description 'May be used to make sure all submodule commits … [See Man Page]'

