# git-tag
# Autogenerated from man page /usr/local/share/man/man1/git-tag.1
# using Deroffing man parser
complete -c git-tag -l '[no-]merged' --description 'Only list tags whose tips are reachable, or not… [See Man Page]'
complete -c git-tag -l no-merged --description 'is used, from the specified commit (HEAD if not specified).'

