# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
# using Deroffing man parser
complete -c git-rebase -l no-autostash --description 'Automatically create a temporary stash before t… [See Man Page]'

