# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -o local --description 'is appended to the format (e. g.'
complete -c git-log -l 'relative.' --description '.'

