# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
# using Deroffing man parser
complete -c git-format-patch -l zero-commit --description 'Output an all-zero hash in each patch\\(cqs From… [See Man Page]'

