# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -o local --description 'is appended to the format (e. g.'
complete -c git-rev-list -l raw --description 'or.'
complete -c git-rev-list -l 'relative.' --description '.'

