# git-cherry-pick
# Autogenerated from man page /usr/local/share/man/man1/git-cherry-pick.1
# using Deroffing man parser
complete -c git-cherry-pick -o 'S[<keyid>]' --description 'GPG-sign commits.'

