# gitk
# Autogenerated from man page /usr/local/share/man/man1/gitk.1
# using Deroffing man parser
complete -c gitk -l all --description 'Show all refs (branches, tags, etc. ).'
complete -c gitk -l 'branches[' -l 'tags[' -l 'remotes[' --description 'Pretend as if all the branches (tags, remote branches, resp.'
complete -c gitk -l since --description 'Show commits more recent than a specific date.'
complete -c gitk -l until --description 'Show commits older than a specific date.'
complete -c gitk -l date-order --description 'Sort commits by date when possible.'
complete -c gitk -l merge --description 'After an attempt to merge stops with conflicts,… [See Man Page]'
complete -c gitk -l left-right --description 'Mark which side of a symmetric diff a commit is reachable from.'
complete -c gitk -l full-history --description 'When filtering history with <path>.'
complete -c gitk -l simplify-merges --description 'Additional option to --full-history to remove s… [See Man Page]'
complete -c gitk -l ancestry-path --description 'When given a range of commits to display (e. g.  commit1.'
complete -c gitk -o 'L<start>' -o 'L:<funcname>:<file>' --description 'Trace the evolution of the line range given by … [See Man Page]'
complete -c gitk -l argscmd --description 'Command to be run each time gitk has to determi… [See Man Page]'
complete -c gitk -l select-commit --description 'Select the specified commit after loading the graph.'
complete -c gitk -o 'L.' --description '.'
complete -c gitk -s L --description 'range, if any, otherwise from the start of file.'

