# glibtool
# Autogenerated from man page /usr/local/share/man/man1/glibtool.1
# using Deroffing man parser
complete -c glibtool -l config --description 'show all configuration variables.'
complete -c glibtool -l debug --description 'enable verbose shell tracing.'
complete -c glibtool -s n -l dry-run --description 'display commands without modifying any files.'
complete -c glibtool -l features --description 'display basic configuration information and exit.'
complete -c glibtool -l mode --description 'use operation mode MODE.'
complete -c glibtool -l no-warnings --description 'equivalent to \'-Wnone\'.'
complete -c glibtool -l preserve-dup-deps --description 'don\'t remove duplicate dependency libraries.'
complete -c glibtool -l quiet -l silent --description 'don\'t print informational messages.'
complete -c glibtool -l tag --description 'use configuration variables from tag TAG.'
complete -c glibtool -s v -l verbose --description 'print more informational messages than default.'
complete -c glibtool -l version --description 'print version information.'
complete -c glibtool -s W -l warnings --description 'report the warnings falling in CATEGORY [all].'
complete -c glibtool -s h -l help -l help-all --description 'print short, long, or detailed help message .'

