# gnutls-cli
# Autogenerated from man page /usr/local/share/man/man1/gnutls-cli.1
# using Type1
complete -c gnutls-cli -o 'no-tofu\\f[]' --description 'Enable trust on first use authentication.'
complete -c gnutls-cli -o 'no-strict-tofu\\f[]' --description 'Fail to connect if a known certificate has changed.'
complete -c gnutls-cli -o 'no-dane\\f[]' --description 'Enable DANE certificate verification (DNSSEC).'
complete -c gnutls-cli -o 'no-local-dns\\f[]' --description 'Use the local DNS server for DNSSEC resolving.'
complete -c gnutls-cli -o 'no-ca-verification\\f[]' --description 'Enable CA certificate verification.'
complete -c gnutls-cli -o 'no-ocsp\\f[]' --description 'Enable OCSP certificate verification.'

