# gnutls-certtool
# Autogenerated from man page /usr/local/share/man/man1/gnutls-certtool.1
# using Type1
complete -c gnutls-certtool -o 'no-p7-include-cert\\f[]' --description 'The signer\'s certificate will be included in the cert list.'
complete -c gnutls-certtool -o 'no-p7-show-data\\f[]' --description 'Will show the embedded data in the PKCS #7 structure.'
complete -c gnutls-certtool -o 'no-inder\\f[]' --description 'Use DER format for input certificates, private … [See Man Page]'
complete -c gnutls-certtool -o 'no-outder\\f[]' --description 'Use DER format for output certificates, private… [See Man Page]'

