# gtf
# Autogenerated from man page /opt/X11/share/man/man1/gtf.1
# using Deroffing man parser
complete -c gtf -s v -l verbose --description 'Enable verbose printouts  This shows a trace fo… [See Man Page]'
complete -c gtf -s x -l xorgmode --description 'Print the mode parameters as Xorg-style mode lines.'
complete -c gtf -s f -l fbset --description 'Print the mode parameters in a format suitable for fbset(8) .'

