# gtk-update-icon-cache
# Autogenerated from man page /usr/local/share/man/man1/gtk-update-icon-cache.1
# using Deroffing man parser
complete -c gtk-update-icon-cache -l force -s f --description 'Overwrite an existing cache file even if it app… [See Man Page]'
complete -c gtk-update-icon-cache -l ignore-theme-index -s t --description 'Don\\*(Aqt check for the existence of index.'
complete -c gtk-update-icon-cache -l index-only -s i --description 'Don\\*(Aqt include image data in the cache.'
complete -c gtk-update-icon-cache -l include-image-data --description 'Include image data in the cache.'
complete -c gtk-update-icon-cache -l source -s c --description 'Output a C header file declaring a constant NAM… [See Man Page]'
complete -c gtk-update-icon-cache -l quiet -s q --description 'Turn off verbose output.'
complete -c gtk-update-icon-cache -l validate -s v --description 'Validate existing icon cache.'

