# gtk-query-immodules-3
# Autogenerated from man page /usr/local/share/man/man1/gtk-query-immodules-3.0.1
# using Deroffing man parser
complete -c gtk-query-immodules-3 -l update-cache --description 'Write the output to the default cache location … [See Man Page]'

