# gtk-launch
# Autogenerated from man page /usr/local/share/man/man1/gtk-launch.1
# using Deroffing man parser
complete -c gtk-launch -s '?' -l help --description 'Prints a short help text and exits.'

