# gtk-encode-symbolic-svg
# Autogenerated from man page /usr/local/share/man/man1/gtk-encode-symbolic-svg.1
# using Deroffing man parser
complete -c gtk-encode-symbolic-svg -s o -l output --description 'Write png files to DIRECTORY instead of the cur… [See Man Page]'

