# gtk3-widget-factory
# Autogenerated from man page /usr/local/share/man/man1/gtk3-widget-factory.1
# using Deroffing man parser
complete -c gtk3-widget-factory -s h -l help --description 'Show help options.'

