# gtk3-demo
# Autogenerated from man page /usr/local/share/man/man1/gtk3-demo.1
# using Deroffing man parser
complete -c gtk3-demo -s h -l help --description 'Show help options.'
complete -c gtk3-demo -l list --description 'List available examples.'
complete -c gtk3-demo -o run --description 'Run the named example.'
complete -c gtk3-demo -l autoquit --description 'Quit after a short timeout.'
complete -c gtk3-demo -l run --description '.'

