# gtk3-icon-browser
# Autogenerated from man page /usr/local/share/man/man1/gtk3-icon-browser.1
# using Deroffing man parser
complete -c gtk3-icon-browser -s h -l help --description 'Show help options.'

