# gv2gxl
# Autogenerated from man page /usr/local/share/man/man1/gv2gxl.1
# using Deroffing man parser
complete -c gv2gxl -s g --description 'The command name and input file extensions are … [See Man Page]'
complete -c gv2gxl -s d --description 'The command name and input file extensions are … [See Man Page]'
complete -c gv2gxl -s '?' --description 'Prints usage information and exits.'
complete -c gv2gxl -s o --description 'If specified, the output will be written into the file outfile.'

