# gvmap
# Autogenerated from man page /usr/local/share/man/man1/gvmap.sh.1
# using Deroffing man parser
complete -c gvmap -s K --description 'specifies which program should be use for the initial layout.'
complete -c gvmap -s T --description 'specifies the final output format.'
complete -c gvmap -s N --description 'specifies the setting of a default node attribu… [See Man Page]'
complete -c gvmap -s G --description 'specifies the setting of a graph attribute duri… [See Man Page]'
complete -c gvmap -s E --description 'specifies the setting of a default edge attribu… [See Man Page]'
complete -c gvmap -s n --description 'specifies the setting of a default node attribu… [See Man Page]'
complete -c gvmap -s A --description 'specifies a flag to be passed to gvmap.  For example, gvmap.'
complete -c gvmap -s V --description 'Print version information and exit.'

