# gvpack
# Autogenerated from man page /usr/local/share/man/man1/gvpack.1
# using Deroffing man parser
complete -c gvpack -s g --description 'Combines the graphs at the graph level.'
complete -c gvpack -o 'array[_flags][n]' --description 'Combines the graphs at the graph level, placing… [See Man Page]'
complete -c gvpack -s G --description 'Specifies attributes to be added to the resulting union graph.'
complete -c gvpack -s m --description 'Packs the graphs allowing a margin of output po… [See Man Page]'
complete -c gvpack -s n --description 'Combines the graphs at the node level.'
complete -c gvpack -s o --description 'Prints output to the file output.'
complete -c gvpack -s s --description 'Use graph_name as the name of the root graph.'
complete -c gvpack -s u --description 'Don\'t pack the graphs.  Just combine them into a single graph.'
complete -c gvpack -s v --description 'Verbose mode.'
complete -c gvpack -s '?' --description 'Prints usage information and exit.'

