# gvpr
# Autogenerated from man page /usr/local/share/man/man1/gvpr.1
# using Deroffing man parser
complete -c gvpr -s a --description 'The string args is split into whitespace\\(hysep… [See Man Page]'
complete -c gvpr -s c --description 'Use the source graph as the output graph.'
complete -c gvpr -s i --description 'Derive the node\\(hyinduced subgraph extension o… [See Man Page]'
complete -c gvpr -s o --description 'Causes the output stream to be written to the s… [See Man Page]'
complete -c gvpr -s f --description 'Use the contents of the specified file as the p… [See Man Page]'
complete -c gvpr -s q --description 'Turns off warning messages.'
complete -c gvpr -s n --description 'Turns off graph read-ahead.'
complete -c gvpr -s V --description 'Causes the program to print version information and exit.'
complete -c gvpr -s '?' --description 'Causes the program to print usage information and exit.'

