# gxl2gv
# Autogenerated from man page /usr/local/share/man/man1/gxl2gv.1
# using Deroffing man parser
complete -c gxl2gv -s g --description 'The command name and input file extensions are … [See Man Page]'
complete -c gxl2gv -s d --description 'The command name and input file extensions are … [See Man Page]'
complete -c gxl2gv -s '?' --description 'Prints usage information and exits.'
complete -c gxl2gv -s o --description 'If specified, the output will be written into the file outfile.'

