# headerdoc2html
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/headerdoc2html.1
# using Darwin man parser
complete -c headerdoc2html -s H --description 'The H option turns on inclusion of the htmlHead… [See Man Page]'
complete -c headerdoc2html -s X --description 'The X option switches from HTML to XML output.'
complete -c headerdoc2html -s d --description 'The d option turns on extra debugging output.'
complete -c headerdoc2html -s h --description 'The h option causes headerdoc to output an XML … [See Man Page]'
complete -c headerdoc2html -s p --description 'The p option turns on the C preprocessor.'
complete -c headerdoc2html -s q --description 'The q option causes headerdoc to be excessively quiet.'
complete -c headerdoc2html -s u --description 'The u option causes headerdoc to produce unsorted output.'
complete -c headerdoc2html -s v --description 'The v option causes headerdoc to print version information.'

