# htcacheclean
# Autogenerated from man page /usr/share/man/man8/htcacheclean.8
# using Deroffing man parser
complete -c htcacheclean -s A --description 'List the URLs currently stored in the cache, al… [See Man Page]'

