# iceauth
# Autogenerated from man page /opt/X11/share/man/man1/iceauth.1
# using Deroffing man parser
complete -c iceauth -s f --description '             the file currently in use by the session.'
complete -c iceauth -s v --description '.'
complete -c iceauth -s q --description '.'
complete -c iceauth -s i --description '.'
complete -c iceauth -s b --description '.'
complete -c iceauth -s u --description '.'

