# install_name_tool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/install_name_tool.1
# using Deroffing man parser
complete -c install_name_tool -o change --description 'Changes the dependent shared library install na… [See Man Page]'
complete -c install_name_tool -o id --description 'Changes the shared library identification name … [See Man Page]'
complete -c install_name_tool -o rpath --description 'Changes the rpath path name  old to  new in the… [See Man Page]'
complete -c install_name_tool -o add_rpath --description 'Adds the rpath path name  new in the specified Mach-O binary.'
complete -c install_name_tool -o headerpad_max_install_names --description 'option.'
complete -c install_name_tool -o delete_rpath --description 'deletes the rpath path name old in the specified Mach-O binary.'

