# lefty
# Autogenerated from man page /usr/local/share/man/man1/lefty.1
# using Deroffing man parser
complete -c lefty -s x --description 'Instructs the editor to exit after processing  file .'
complete -c lefty -s e --description '<expression> is parsed and executed.'
complete -c lefty -o el --description 'Set error reporting level.  The default value is  0 .'
complete -c lefty -o sd --description 'Specifies how much of the stack to show, when a… [See Man Page]'
complete -c lefty -o sb --description 'Specifies how much of each function in the stac… [See Man Page]'
complete -c lefty -o df --description 'Sets the default font.'
complete -c lefty -o ps --description 'Specifies a default file name for postscript files.'
complete -c lefty -s V --description 'Prints the version.'
complete -c lefty -s '?' --description 'Prints the usage and exits.  SEE ALSO lefty user guide.'

