# lipo
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/lipo.1
# using Deroffing man parser
complete -c lipo -o info --description 'Briefly list the architecture types in the inpu… [See Man Page]'
complete -c lipo -o detailed_info --description 'Display a detailed list of the architecture typ… [See Man Page]'
complete -c lipo -o arch --description 'Tells  lipo that  input_file contains the speci… [See Man Page]'
complete -c lipo -o arch_blank --description 'Specifies that the output for the specified R a… [See Man Page]'
complete -c lipo -o output --description 'Specifies its argument to be the output file.'
complete -c lipo -o create --description 'Take the input files (or file) and create one u… [See Man Page]'
complete -c lipo -o thin --description 'Take one input file and create a thin output fi… [See Man Page]'
complete -c lipo -o replace --description 'Take one universal input file; in the output fi… [See Man Page]'
complete -c lipo -o remove --description 'Take one universal input file and remove the  a… [See Man Page]'
complete -c lipo -o extract --description 'Take one universal input file and copy the  arc… [See Man Page]'
complete -c lipo -o extract_family --description 'Take one universal input file and copy all of t… [See Man Page]'
complete -c lipo -o verify_arch --description 'Take one input file and verify the specified R … [See Man Page]'
complete -c lipo -o segalign --description 'which are used in combination with other options.'

