# lldb
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/lldb.1
# using Darwin man parser
complete -c lldb -s h --description 'Prints out the usage information for the lldb debugger.'
complete -c lldb -s v --description 'Prints out the version number of the lldb debugger.'
complete -c lldb -s a --description 'Specifies which architecture lldb will use when… [See Man Page]'
complete -c lldb -s f --description 'Specifies the executable file that lldb will be… [See Man Page]'
complete -c lldb -s n --description 'Specifies the name of a currently-running process to attach to.'
complete -c lldb -s w --description 'When used in concert with n Ar process-name, in… [See Man Page]'
complete -c lldb -s p --description 'Specifies a currently running process that lldb… [See Man Page]'
complete -c lldb -s c --description 'Specifies the core file to examine.'
complete -c lldb -s l --description 'Tells the debugger to use the specified scripti… [See Man Page]'
complete -c lldb -s d --description 'Tells the debugger to print out extra informati… [See Man Page]'
complete -c lldb -s s --description 'Tells lldb to read in and execute the file file… [See Man Page]'
complete -c lldb -s e --description 'Instructs lldb to open source files using the h… [See Man Page]'
complete -c lldb -s x --description 'Do not automatically parse any \'. lldbinit\' files.'

