# llvm-profdata
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/llvm-profdata.1
# using Deroffing man parser
complete -c llvm-profdata -o help --description 'Print a summary of command line options.'
complete -c llvm-profdata -o output -s o --description 'Specify the output file name.'
complete -c llvm-profdata -o instr --description 'Specify that the input profile is an instrument… [See Man Page]'
complete -c llvm-profdata -o sample --description 'Specify that the input profile is a sample-based profile.'
complete -c llvm-profdata -o binary --description 'Emit the profile using a binary encoding.'
complete -c llvm-profdata -o text --description 'Emit the profile in text mode.'
complete -c llvm-profdata -o gcc --description 'Emit the profile using GCC\'s gcov format (Not yet supported).'
complete -c llvm-profdata -o all-functions --description 'Print details for every function.'
complete -c llvm-profdata -o counts --description 'Print the counter values for the displayed functions.'
complete -c llvm-profdata -o function --description 'Print details for a function if the function\'s … [See Man Page]'

