# lneato
# Autogenerated from man page /usr/local/share/man/man1/lneato.1
# using Deroffing man parser
complete -c lneato -s V --description 'Prints the version.'
complete -c lneato -o lm --description 'Sets the layout mode.  The mode can be sync or async.'
complete -c lneato -o el --description 'Sets the mesage level.  The lev can be 0 or 1.'

