# logresolve
# Autogenerated from man page /usr/share/man/man1/logresolve.1
# using Deroffing man parser
complete -c logresolve -s c --description 'This causes logresolve to apply some DNS checks… [See Man Page]'

