# luajit
# Autogenerated from man page /usr/local/share/man/man1/luajit.1
# using Deroffing man parser
complete -c luajit -s e --description 'Run the given chunk of Lua code.'
complete -c luajit -s l --description 'Load the named library, just like require("library").'
complete -c luajit -s b --description 'Save or list bytecode.'
complete -c luajit -s j --description 'Perform LuaJIT control command (optional space after -j).'
complete -c luajit -s O --description 'Control LuaJIT optimizations.'
complete -c luajit -s i --description 'Run in interactive mode.'
complete -c luajit -s v --description 'Show LuaJIT version.'
complete -c luajit -s E --description 'Ignore environment variables.'

