# MagickWand-config
# Autogenerated from man page /usr/local/share/man/man1/MagickWand-config.1
# using Deroffing man parser
complete -c MagickWand-config -l cflags --description 'Print the compiler flags that were used to compile   libWand .'
complete -c MagickWand-config -l cppflags --description 'Print the preprocessor flags that are needed to… [See Man Page]'
complete -c MagickWand-config -l exec-prefix --description 'Print the directory under which target specific… [See Man Page]'
complete -c MagickWand-config -l ldflags --description 'Print the linker flags that are needed to link … [See Man Page]'
complete -c MagickWand-config -l libs --description 'Print the linker flags that are needed to link … [See Man Page]'
complete -c MagickWand-config -l version --description 'Print the version of the Wand distribution to standard output.'

