# MagickCore-config
# Autogenerated from man page /usr/local/share/man/man1/MagickCore-config.1
# using Darwin man parser
complete -c MagickCore-config -l cppflags --description 'Print the compiler flags that are needed to fin… [See Man Page]'
complete -c MagickCore-config -l prefix --description 'Print the directory under which target specific… [See Man Page]'
complete -c MagickCore-config -l ldflags --description 'Print the linker flags that are needed to link … [See Man Page]'
complete -c MagickCore-config -l version --description 'Print the version of the ImageMagick 1 distribu… [See Man Page]'
complete -c MagickCore-config -l coder-path --description 'Print the path where the ImageMagick 1 coder mo… [See Man Page]'
complete -c MagickCore-config -l filter-path --description 'Print the path where the ImageMagick 1 filter m… [See Man Page]'

