# MergePef
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/MergePef.1
# using Darwin man parser
complete -c MergePef -s v --description 'Produce verbose diagnostics to standard output.'
complete -c MergePef -s t --description 'Set the Extended HFS file type of the output file.'
complete -c MergePef -s c --description 'Set the Extended HFS file creator of the output file.'
complete -c MergePef -s o --description 'Path to the output file.'

