# mig
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/mig.1
# using Deroffing man parser
complete -c mig -o q/-Q --description 'Omit /  emit warning messages.'
complete -c mig -o v/-V --description 'Verbose mode ( on /  off ) will summarize types… [See Man Page]'
complete -c mig -o l/-L --description 'Controls (  off / on ) whether or not generated… [See Man Page]'
complete -c mig -o k/-K --description 'Controls (  on / off ) whether generated code c… [See Man Page]'
complete -c mig -o s/-S --description 'Controls ( on /  off ) whether generated server… [See Man Page]'
complete -c mig -s i --description 'Specify User file prefix.'
complete -c mig -o user --description 'Specify name of user-side RPC generated source file.'
complete -c mig -o server --description 'Specify name of server-side RPC generated source file.'
complete -c mig -o header --description 'Specify name of user-side generated header file.'
complete -c mig -o sheader --description 'Specify name of server-side generated header file.'
complete -c mig -o iheader --description 'Specify internal header file name.'
complete -c mig -o dheader --description 'Specify defines generated header file.'
complete -c mig -o maxonstack --description 'Specify maximum size of message on stack.'
complete -c mig -o split --description 'Use split headers.'
complete -c mig -o arch --description 'Specify machine architecture for target code.'
complete -c mig -o MD --description 'Option is passed to the C compiler for dependency generation.'
complete -c mig -o cpp --description 'This option is ignored.'
complete -c mig -o cc --description 'Specify pathname to specific C compiler to use … [See Man Page]'
complete -c mig -o migcom --description 'Specify pathname to specific migcom compiler to… [See Man Page]'
complete -c mig -o isysroot --description 'Specify SDK root directory.'

