# mkdep
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/mkdep.1
# using Darwin man parser
complete -c mkdep -s a --description 'Append to the output file, so that multiple mkd… [See Man Page]'
complete -c mkdep -s f --description 'Write the include file dependencies to file, in… [See Man Page]'
complete -c mkdep -s p --description 'Cause mkdep to produce dependencies of the form… [See Man Page]'

