# mm2gv
# Autogenerated from man page /usr/local/share/man/man1/mm2gv.1
# using Deroffing man parser
complete -c mm2gv -s c --description 'This flag causes mm2gv to assign colors to the edges.'
complete -c mm2gv -s l --description 'If set, mm2gv attaches a label to the graph ind… [See Man Page]'
complete -c mm2gv -s u --description 'If specified, the graph is assumed to be undirected.'
complete -c mm2gv -s v --description 'This flag causes mm2gv to store the matrix valu… [See Man Page]'
complete -c mm2gv -s U --description 'Specifies how square matrices are handled.'
complete -c mm2gv -s o --description 'Prints output to the file outfile.'

