# mscgen
# Autogenerated from man page /usr/local/share/man/man1/mscgen.1
# using Deroffing man parser
complete -c mscgen -s T --description 'Specifies the output file type, which maybe one… [See Man Page]'
complete -c mscgen -s i --description 'The file from which to read input.'
complete -c mscgen -s o --description 'Write output to the named file.'
complete -c mscgen -s F --description 'Use specified font for rendering PNG output.'
complete -c mscgen -s p --description 'Display the parsed msc as text to stdout.'
complete -c mscgen -s l --description 'Display program licence and exit.'

