# ndisasm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/ndisasm.1
# using Deroffing man parser
complete -c ndisasm -s h --description 'Causes  ndisasm to exit immediately, after givi… [See Man Page]'
complete -c ndisasm -s r --description 'Causes  ndisasm to exit immediately, after disp… [See Man Page]'
complete -c ndisasm -s o --description 'Specifies the notional load address for the file.'
complete -c ndisasm -s s --description 'Manually specifies a synchronisation address, s… [See Man Page]'
complete -c ndisasm -s e --description 'Specifies a number of bytes to discard from the… [See Man Page]'
complete -c ndisasm -s k --description 'Specifies that  length bytes, starting from dis… [See Man Page]'
complete -c ndisasm -s a -s i --description 'Enables automatic (or intelligent) sync mode, i… [See Man Page]'
complete -c ndisasm -s b --description 'Specifies either 16-bit or 32-bit mode.'
complete -c ndisasm -s u --description 'Specifies 32-bit mode, more compactly than using `-b 32\'.'
complete -c ndisasm -s p --description 'Prefers instructions as defined by vendor in ca… [See Man Page]'

