# nm
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/nm.1
# using Deroffing man parser
complete -c nm -s a --description 'Display all symbol table entries,  including th… [See Man Page]'
complete -c nm -s g --description 'Display only global (external) symbols.'
complete -c nm -s n --description 'Sort numerically rather than alphabetically.'
complete -c nm -s o --description 'Prepend file or archive element name to each ou… [See Man Page]'
complete -c nm -s p --description 'Don\'t sort; display in symbol-table order.'
complete -c nm -s r --description 'Sort in reverse order.'
complete -c nm -s u --description 'Display only undefined symbols.'
complete -c nm -s U --description 'Don\'t display undefined symbols.'
complete -c nm -s m --description 'Display the N_SECT type symbols (Mach-O symbols) as .'
complete -c nm -s x --description 'Display the symbol table entry\'s fields in hexa… [See Man Page]'
complete -c nm -s j --description 'Just display the symbol names (no value or type).'
complete -c nm -s s --description 'List only those symbols in the section  (segname,sectname).'
complete -c nm -s l --description 'List a pseudo symbol  ".'
complete -c nm -o arch --description 'Specifies the architecture,  arch_type, of the … [See Man Page]'
complete -c nm -s f --description 'Display the symbol table of a dynamic library f… [See Man Page]'
complete -c nm -s A --description 'Write the pathname or library name of an object on each line.'
complete -c nm -s P --description 'Write information in a portable output format.'
complete -c nm -s t --description 'For the  -P output, write the numeric value in … [See Man Page]'
complete -c nm -s L --description 'Display the symbols in the bitcode files in the… [See Man Page]'

