# nmedit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/nmedit.1
# using Deroffing man parser
complete -c nmedit -s s --description 'Leave the symbol table entries for the global s… [See Man Page]'
complete -c nmedit -s R --description 'Change the symbol table entries for the global … [See Man Page]'
complete -c nmedit -s p --description 'Change symbols to private externs instead of static.'
complete -c nmedit -s A --description 'Leave all global absolute symbols except those … [See Man Page]'
complete -c nmedit -o arch --description 'Specifies the architecture,  arch_type, of the … [See Man Page]'
complete -c nmedit -s g --description 'option to cc (1)) for the global symbols it cha… [See Man Page]'
complete -c nmedit -s o --description 'Write the result into the file output.'

