# nop
# Autogenerated from man page /usr/local/share/man/man1/nop.1
# using Deroffing man parser
complete -c nop -s p --description 'Produce no output - just check the input for valid DOT.'
complete -c nop -s '?' --description 'Print usage information.'

