# npm-uninstall
# Autogenerated from man page /usr/local/share/man/man1/npm-uninstall.1
# using Deroffing man parser
complete -c npm-uninstall -s S -l save: --description 'o 2.'
complete -c npm-uninstall -s D -l save-dev: --description 'o 2.'
complete -c npm-uninstall -s O -l save-optional: --description 'Further, if you have an npm-shrinkwrap.'

