# npm-dist-tag
# Autogenerated from man page /usr/local/share/man/man1/npm-dist-tag.1
# using Deroffing man parser
complete -c npm-dist-tag -l tag --description 'o 2 rm: Clear a tag that is no longer in use from the package.'

