# ocaml
# Autogenerated from man page /usr/local/share/man/man1/ocaml.1
# using Deroffing man parser
complete -c ocaml -o open --description 'Opens the given module before starting the toplevel.'
complete -c ocaml -o safe-string --description 'Enforce the separation between types  string an… [See Man Page]'
complete -c ocaml -o unsafe-string --description 'Identify the types  string and bytes , thereby … [See Man Page]'

