# ocamldebug
# Autogenerated from man page /usr/local/share/man/man1/ocamldebug.1
# using Deroffing man parser
complete -c ocamldebug -o machine-readable --description 'Print information in a format more suitable for… [See Man Page]'

