# oid2name
# Autogenerated from man page /usr/local/share/man/man1/oid2name.1
# using Deroffing man parser
complete -c oid2name -s f --description 'show info for table with filenode filenode.'
complete -c oid2name -s i --description 'include indexes and sequences in the listing.'
complete -c oid2name -s o --description 'show info for table with OID oid.'
complete -c oid2name -s q --description 'omit headers (useful for scripting).'
complete -c oid2name -s s --description 'show tablespace OIDs.'
complete -c oid2name -s S --description 'include system objects (those in information_sc… [See Man Page]'
complete -c oid2name -s t --description 'show info for table(s) matching tablename_pattern.'
complete -c oid2name -o 'V
.br
--version' --description 'Print the oid2name version and exit.'
complete -c oid2name -s x --description 'display more information about each object show… [See Man Page]'
complete -c oid2name -o '?
.br
--help' --description 'Show help about oid2name command line arguments, and exit.'
complete -c oid2name -s d --description 'database to connect to.'
complete -c oid2name -s H --description 'database server\\*(Aqs host.'
complete -c oid2name -s p --description 'database server\\*(Aqs port.'
complete -c oid2name -s U --description 'user name to connect as.'
complete -c oid2name -s P --description 'password (deprecated \\(em putting this on the c… [See Man Page]'
complete -c oid2name -s V --description '.'
complete -c oid2name -l version --description '.'
complete -c oid2name -s '?' --description '.'
complete -c oid2name -l help --description '.'
complete -c oid2name -o 't.' --description '.'
complete -c oid2name -o 'd.' --description '.'
complete -c oid2name -l -------------------------------- --description '  17228       alvherre  pg_default   17255     … [See Man Page]'
complete -c oid2name -l ----------------------- --description '    1663       pg_default     1664        pg_gl… [See Man Page]'
complete -c oid2name -o rw------- --description '.'
complete -c oid2name -l -------------------- --description '    155173    accounts.'
complete -c oid2name -l ---------------------------------------------------- --description '    155173       accounts   155173  public  pg_… [See Man Page]'

