# opam-admin-stats
# Autogenerated from man page /usr/local/share/man/man1/opam-admin-stats.1
# using Deroffing man parser
complete -c opam-admin-stats -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-admin-stats -l version --description 'Show version information.'

