# opam
# Autogenerated from man page /usr/local/share/man/man1/opam.1
# using Deroffing man parser
complete -c opam -l color --description 'Colorize the output.'
complete -c opam -l criteria --description 'Specify user preferences for dependency solving for this run.'
complete -c opam -l cudf --description 'Debug option: Save the CUDF requests sent to th… [See Man Page]'
complete -c opam -l debug --description 'Print debug message to stderr.'
complete -c opam -l debug-level --description 'Like `--debug\', but allows specifying the debug… [See Man Page]'
complete -c opam -l git-version --description 'Print the git version if it exists and exit.'
complete -c opam -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam -l no-base-packages --description 'Do not install base packages (useful for testing purposes).'
complete -c opam -l no-self-upgrade --description 'OPAM will replace itself with a newer binary fo… [See Man Page]'
complete -c opam -s q -l quiet --description 'Be quiet when installing a new compiler.'
complete -c opam -l root --description 'Use ROOT as the current root path.'
complete -c opam -l safe --description 'Make sure nothing will be automatically updated or rewritten.'
complete -c opam -l solver --description 'Specify the name of the external dependency solver.'
complete -c opam -l strict --description 'Fail whenever an error is found in a package de… [See Man Page]'
complete -c opam -l switch --description 'Use SWITCH as the current compiler switch.'
complete -c opam -l use-internal-solver -l no-aspcud --description 'Force use of internal heuristics, even if an ex… [See Man Page]'
complete -c opam -s v -l verbose --description 'Be more verbose, show package sub-commands and their output.'
complete -c opam -l version --description 'Show version information.'
complete -c opam -s y -l yes --description 'Disable interactive mode and answer yes to all … [See Man Page]'

