# opam-admin-make
# Autogenerated from man page /usr/local/share/man/man1/opam-admin-make.1
# using Deroffing man parser
complete -c opam-admin-make -l compiler --description 'Specify the variable \'ocaml_version\' to be used… [See Man Page]'
complete -c opam-admin-make -s d -l dryrun --description 'Simply display the possible actions instead of executing them.'
complete -c opam-admin-make -l debug --description 'Display debug messages.'
complete -c opam-admin-make -s g -l generate-checksums --description 'Automatically correct the wrong archive checksums.'
complete -c opam-admin-make -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-admin-make -s i -l index --description 'Only build indexes, not package archives.'
complete -c opam-admin-make -s r -l recursive --description 'Recurse among the transitive dependencies of th… [See Man Page]'
complete -c opam-admin-make -l resolve --description 'A more advanced version of `--recursive\' that c… [See Man Page]'
complete -c opam-admin-make -l switch --description 'Specify the variable switch\' to be used to filt… [See Man Page]'
complete -c opam-admin-make -l version --description 'Show version information.'

