# opam-admin
# Autogenerated from man page /usr/local/share/man/man1/opam-admin.1
# using Deroffing man parser
complete -c opam-admin -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-admin -l version --description 'Show version information.'

