# opam-installer
# Autogenerated from man page /usr/local/share/man/man1/opam-installer.1
# using Deroffing man parser
complete -c opam-installer -l docdir --description 'Documentation dir.  Relative to prefix or absolute.'
complete -c opam-installer -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-installer -s i -l install --description 'Install the package (the default).'
complete -c opam-installer -l libdir --description 'OCaml lib dir.  Relative to prefix or absolute.'
complete -c opam-installer -l mandir --description 'Manpages dir.  Relative to prefix or absolute.'
complete -c opam-installer -l name --description 'Specify the package name.'
complete -c opam-installer -l prefix --description 'The prefix to install to.'
complete -c opam-installer -l script --description 'Don\'t execute the commands, but output a shell-… [See Man Page]'
complete -c opam-installer -l stubsdir --description 'Stubs installation dir.  Relative to prefix or absolute.'
complete -c opam-installer -l topdir --description 'Toplevel install dir.  Relative to prefix or absolute.'
complete -c opam-installer -s u -l uninstall -l remove --description 'Remove the package.'
complete -c opam-installer -l version --description 'Show version information.'

