# opam-admin-depexts
# Autogenerated from man page /usr/local/share/man/man1/opam-admin-depexts.1
# using Deroffing man parser
complete -c opam-admin-depexts -l dep --description 'Extdep tag.'
complete -c opam-admin-depexts -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-admin-depexts -l os --description 'Operating system tag.'
complete -c opam-admin-depexts -l version --description 'Show version information.'

