# opam-admin-check
# Autogenerated from man page /usr/local/share/man/man1/opam-admin-check.1
# using Deroffing man parser
complete -c opam-admin-check -l 'help[' --description 'Show this help in format FMT (pager, plain or groff).'
complete -c opam-admin-check -s n -l normalize --description 'Normalize all files in the repository.'
complete -c opam-admin-check -l version --description 'Show version information.'

