# p11tool
# Autogenerated from man page /usr/local/share/man/man1/p11tool.1
# using Type1
complete -c p11tool -o 'no-mark-wrap\\f[]' --description 'Marks the generated key to be a wrapping key.'
complete -c p11tool -o 'no-mark-trusted\\f[]' --description 'Marks the object to be written as trusted.'
complete -c p11tool -o 'no-mark-decrypt\\f[]' --description 'Marks the object to be written for decryption.'
complete -c p11tool -o 'no-mark-sign\\f[]' --description 'Marks the object to be written for signature generation.'
complete -c p11tool -o 'no-mark-ca\\f[]' --description 'Marks the object to be written as a CA.'
complete -c p11tool -o 'no-mark-private\\f[]' --description 'Marks the object to be written as private.'
complete -c p11tool -o 'no-login\\f[]' --description 'Force (user) login to token.'
complete -c p11tool -o 'no-so-login\\f[]' --description 'Force security officer login to token.'
complete -c p11tool -o 'no-inder\\f[]' --description 'Use DER/RAW format for input.'
complete -c p11tool -o 'no-outder\\f[]' --description 'Use DER format for output certificates, private… [See Man Page]'
complete -c p11tool -o 'no-detailed-url\\f[]' --description 'Print detailed URLs.'

