# pagestuff
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/pagestuff.1
# using Deroffing man parser
complete -c pagestuff -o arch --description 'Specifies the architecture,  arch_type, of the … [See Man Page]'
complete -c pagestuff -s a --description 'Displays all pages.   All other arguments are ignored.'
complete -c pagestuff -s p --description 'Print a list of the sections of the specified M… [See Man Page]'

