# pal2rgb
# Autogenerated from man page /usr/local/share/man/man1/pal2rgb.1
# using Deroffing man parser
complete -c pal2rgb -s C --description 'This option overrides the default behavior of  … [See Man Page]'
complete -c pal2rgb -s p --description 'Explicitly select the planar configuration used… [See Man Page]'
complete -c pal2rgb -s c --description 'Use the specific compression algorithm to encod… [See Man Page]'
complete -c pal2rgb -s r --description 'Explicitly specify the number of rows in each s… [See Man Page]'

