# pcre-config
# Autogenerated from man page /usr/local/share/man/man1/pcre-config.1
# using Deroffing man parser
complete -c pcre-config -l prefix --description 'Writes the directory prefix used in the PCRE in… [See Man Page]'
complete -c pcre-config -l exec-prefix --description 'Writes the directory prefix used in the PCRE in… [See Man Page]'
complete -c pcre-config -l version --description 'Writes the version number of the installed PCRE… [See Man Page]'
complete -c pcre-config -l libs --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l libs16 --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l libs32 --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l libs-cpp --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l libs-posix --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l cflags --description 'Writes to the standard output the command line … [See Man Page]'
complete -c pcre-config -l cflags-posix --description 'Writes to the standard output the command line … [See Man Page]'

