# pg_archivecleanup
# Autogenerated from man page /usr/local/share/man/man1/pg_archivecleanup.1
# using Deroffing man parser
complete -c pg_archivecleanup -s d --description 'Print lots of debug logging output on stderr.'
complete -c pg_archivecleanup -s n --description 'Print the names of the files that would have be… [See Man Page]'
complete -c pg_archivecleanup -o 'V
.br
--version' --description 'Print the pg_archivecleanup version and exit.'
complete -c pg_archivecleanup -s x --description 'When using the program as a standalone utility,… [See Man Page]'
complete -c pg_archivecleanup -o '?
.br
--help' --description 'Show help about pg_archivecleanup command line … [See Man Page]'
complete -c pg_archivecleanup -s V --description '.'
complete -c pg_archivecleanup -l version --description '.'
complete -c pg_archivecleanup -s '?' --description '.'
complete -c pg_archivecleanup -l help --description '.'

