# pg_ctl
# Autogenerated from man page /usr/local/share/man/man1/pg_ctl.1
# using Deroffing man parser
complete -c pg_ctl -o 'c
.br
--core-file' --description 'Attempt to allow server crashes to produce core… [See Man Page]'
complete -c pg_ctl -s D --description 'Specifies the file system location of the datab… [See Man Page]'
complete -c pg_ctl -s l --description 'Append the server log output to filename.'
complete -c pg_ctl -s m --description 'Specifies the shutdown mode.'
complete -c pg_ctl -s o --description 'Specifies options to be passed directly to the … [See Man Page]'
complete -c pg_ctl -s p --description 'Specifies the location of the postgres executable.'
complete -c pg_ctl -o 's
.br
--silent' --description 'Print only errors, no informational messages.'
complete -c pg_ctl -o 't
.br
--timeout' --description 'The maximum number of seconds to wait when wait… [See Man Page]'
complete -c pg_ctl -o 'V
.br
--version' --description 'Print the pg_ctl version and exit.'
complete -c pg_ctl -s w --description 'Wait for the startup or shutdown to complete.'
complete -c pg_ctl -s W --description 'Do not wait for startup or shutdown to complete.'
complete -c pg_ctl -o '?
.br
--help' --description 'Show help about pg_ctl command line arguments, and exit.'
complete -c pg_ctl -s e --description 'Name of the event source for pg_ctl to use for … [See Man Page]'
complete -c pg_ctl -s N --description 'Name of the system service to register.'
complete -c pg_ctl -s P --description 'Password for the user to start the service.'
complete -c pg_ctl -s S --description 'Start type of the system service to register.'
complete -c pg_ctl -s U --description 'User name for the user to start the service.'
complete -c pg_ctl -l help --description 'to see a list of supported signal names.'
complete -c pg_ctl -s c --description '.'
complete -c pg_ctl -l core-file --description '.'
complete -c pg_ctl -l pgdata --description '.'
complete -c pg_ctl -l log --description '.'
complete -c pg_ctl -l mode --description '.'
complete -c pg_ctl -s s --description '.'
complete -c pg_ctl -l silent --description '.'
complete -c pg_ctl -s t --description '.'
complete -c pg_ctl -l timeout --description '.'
complete -c pg_ctl -s V --description '.'
complete -c pg_ctl -l version --description '.'
complete -c pg_ctl -s '?' --description '.'

