# pg_controldata
# Autogenerated from man page /usr/local/share/man/man1/pg_controldata.1
# using Deroffing man parser
complete -c pg_controldata -s V --description 'and.'
complete -c pg_controldata -l version --description 'pg_controldata version and exit.  It also supports options.'
complete -c pg_controldata -s '?' --description 'and.'
complete -c pg_controldata -l help --description 'ENVIRONMENT.'

