# pg_dumpall
# Autogenerated from man page /usr/local/share/man/man1/pg_dumpall.1
# using Deroffing man parser
complete -c pg_dumpall -o 'a
.br
--data-only' --description 'Dump only the data, not the schema (data definitions).'
complete -c pg_dumpall -o 'c
.br
--clean' --description 'Include SQL commands to clean (drop) databases … [See Man Page]'
complete -c pg_dumpall -s f --description 'Send output to the specified file.'
complete -c pg_dumpall -o 'g
.br
--globals-only' --description 'Dump only global objects (roles and tablespaces), no databases.'
complete -c pg_dumpall -o 'o
.br
--oids' --description 'Dump object identifiers (OIDs) as part of the d… [See Man Page]'
complete -c pg_dumpall -o 'O
.br
--no-owner' --description 'Do not output commands to set ownership of obje… [See Man Page]'
complete -c pg_dumpall -o 'r
.br
--roles-only' --description 'Dump only roles, no databases or tablespaces.'
complete -c pg_dumpall -o 's
.br
--schema-only' --description 'Dump only the object definitions (schema), not data.'
complete -c pg_dumpall -s S --description 'Specify the superuser user name to use when disabling triggers.'
complete -c pg_dumpall -o 't
.br
--tablespaces-only' --description 'Dump only tablespaces, no databases or roles.'
complete -c pg_dumpall -o 'v
.br
--verbose' --description 'Specifies verbose mode.'
complete -c pg_dumpall -o 'V
.br
--version' --description 'Print the pg_dumpall version and exit.'
complete -c pg_dumpall -o 'x
.br
--no-privileges
.br
--no-acl' --description 'Prevent dumping of access privileges (grant/revoke commands).'
complete -c pg_dumpall -l binary-upgrade --description 'This option is for use by in-place upgrade utilities.'
complete -c pg_dumpall -l 'column-inserts
.br
--attribute-inserts' --description 'Dump data as INSERT commands with explicit colu… [See Man Page]'
complete -c pg_dumpall -l disable-dollar-quoting --description 'This option disables the use of dollar quoting … [See Man Page]'
complete -c pg_dumpall -l disable-triggers --description 'This option is relevant only when creating a data-only dump.'
complete -c pg_dumpall -l if-exists --description 'Use conditional commands (i. e.'
complete -c pg_dumpall -l inserts --description 'Dump data as INSERT commands (rather than COPY).'
complete -c pg_dumpall -l lock-wait-timeout --description 'Do not wait forever to acquire shared table loc… [See Man Page]'
complete -c pg_dumpall -l no-security-labels --description 'Do not dump security labels.'
complete -c pg_dumpall -l no-tablespaces --description 'Do not output commands to create tablespaces no… [See Man Page]'
complete -c pg_dumpall -l no-unlogged-table-data --description 'Do not dump the contents of unlogged tables.'
complete -c pg_dumpall -l quote-all-identifiers --description 'Force quoting of all identifiers.'
complete -c pg_dumpall -l use-set-session-authorization --description 'Output SQL-standard SET SESSION AUTHORIZATION c… [See Man Page]'
complete -c pg_dumpall -o '?
.br
--help' --description 'Show help about pg_dumpall command line arguments, and exit.'
complete -c pg_dumpall -s d --description 'Specifies parameters used to connect to the ser… [See Man Page]'
complete -c pg_dumpall -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c pg_dumpall -s l --description 'Specifies the name of the database to connect t… [See Man Page]'
complete -c pg_dumpall -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c pg_dumpall -s U --description 'User name to connect as.'
complete -c pg_dumpall -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c pg_dumpall -o 'W
.br
--password' --description 'Force pg_dumpall to prompt for a password befor… [See Man Page]'
complete -c pg_dumpall -l role --description 'Specifies a role name to be used to create the dump.'
complete -c pg_dumpall -s a --description '.'
complete -c pg_dumpall -l data-only --description '.'
complete -c pg_dumpall -s c --description '.'
complete -c pg_dumpall -l clean --description '.'
complete -c pg_dumpall -l file --description '.'
complete -c pg_dumpall -s g --description '.'
complete -c pg_dumpall -l globals-only --description '.'
complete -c pg_dumpall -s o --description '.'
complete -c pg_dumpall -l oids --description '.'
complete -c pg_dumpall -s O --description '.'
complete -c pg_dumpall -l no-owner --description '.'
complete -c pg_dumpall -o 'O.' --description '.'
complete -c pg_dumpall -s r --description '.'
complete -c pg_dumpall -l roles-only --description '.'
complete -c pg_dumpall -s s --description '.'
complete -c pg_dumpall -l schema-only --description '.'
complete -c pg_dumpall -l superuser --description '.'
complete -c pg_dumpall -s t --description '.'
complete -c pg_dumpall -l tablespaces-only --description '.'
complete -c pg_dumpall -s v --description '.'
complete -c pg_dumpall -l verbose --description '.'
complete -c pg_dumpall -s V --description '.'
complete -c pg_dumpall -l version --description '.'
complete -c pg_dumpall -s x --description '.'
complete -c pg_dumpall -l no-privileges --description '.'
complete -c pg_dumpall -l no-acl --description '.'
complete -c pg_dumpall -l column-inserts --description '.'
complete -c pg_dumpall -l attribute-inserts --description '.'
complete -c pg_dumpall -s '?' --description '.'
complete -c pg_dumpall -l help --description '.'
complete -c pg_dumpall -l dbname --description '.'
complete -c pg_dumpall -l host --description '.'
complete -c pg_dumpall -l database --description '.'
complete -c pg_dumpall -l port --description '.'
complete -c pg_dumpall -l username --description '.'
complete -c pg_dumpall -s w --description '.'
complete -c pg_dumpall -l no-password --description '.'
complete -c pg_dumpall -s W --description '.'
complete -c pg_dumpall -l password --description '.'
complete -c pg_dumpall -o 'U)' --description 'pg_dumpall, but can switch to a role with the required rights.'

