# pg_isready
# Autogenerated from man page /usr/local/share/man/man1/pg_isready.1
# using Deroffing man parser
complete -c pg_isready -s d --description 'Specifies the name of the database to connect to.'
complete -c pg_isready -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c pg_isready -s p --description 'Specifies the TCP port or the local Unix-domain… [See Man Page]'
complete -c pg_isready -o 'q
.br
--quiet' --description 'Do not display status message.  This is useful when scripting.'
complete -c pg_isready -s t --description 'The maximum number of seconds to wait when atte… [See Man Page]'
complete -c pg_isready -s U --description 'Connect to the database as the user username in… [See Man Page]'
complete -c pg_isready -o 'V
.br
--version' --description 'Print the pg_isready version and exit.'
complete -c pg_isready -o '?
.br
--help' --description 'Show help about pg_isready command line arguments, and exit.'
complete -c pg_isready -l dbname --description '.'
complete -c pg_isready -l host --description '.'
complete -c pg_isready -l port --description '.'
complete -c pg_isready -s q --description '.'
complete -c pg_isready -l quiet --description '.'
complete -c pg_isready -l timeout --description '.'
complete -c pg_isready -l username --description '.'
complete -c pg_isready -s V --description '.'
complete -c pg_isready -l version --description '.'
complete -c pg_isready -s '?' --description '.'
complete -c pg_isready -l help --description '.'

