# pg_receivexlog
# Autogenerated from man page /usr/local/share/man/man1/pg_receivexlog.1
# using Deroffing man parser
complete -c pg_receivexlog -s D --description 'Directory to write the output to.'
complete -c pg_receivexlog -l if-not-exists --description 'Do not not error out when --create-slot is spec… [See Man Page]'
complete -c pg_receivexlog -o 'n
.br
--no-loop' --description 'Don\\*(Aqt loop on connection errors.'
complete -c pg_receivexlog -s s --description 'Specifies the number of seconds between status … [See Man Page]'
complete -c pg_receivexlog -s S --description 'Require pg_receivexlog to use an existing repli… [See Man Page]'
complete -c pg_receivexlog -l synchronous --description 'Flush the WAL data to disk immediately after it… [See Man Page]'
complete -c pg_receivexlog -o 'v
.br
--verbose' --description 'Enables verbose mode.'
complete -c pg_receivexlog -s d --description 'Specifies parameters used to connect to the ser… [See Man Page]'
complete -c pg_receivexlog -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c pg_receivexlog -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c pg_receivexlog -s U --description 'User name to connect as.'
complete -c pg_receivexlog -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c pg_receivexlog -o 'W
.br
--password' --description 'Force pg_receivexlog to prompt for a password b… [See Man Page]'
complete -c pg_receivexlog -l create-slot --description 'Create a new physical replication slot with the… [See Man Page]'
complete -c pg_receivexlog -l drop-slot --description 'Drop the replication slot with the name specifi… [See Man Page]'
complete -c pg_receivexlog -o 'V
.br
--version' --description 'Print the pg_receivexlog version and exit.'
complete -c pg_receivexlog -o '?
.br
--help' --description 'Show help about pg_receivexlog command line arg… [See Man Page]'
complete -c pg_receivexlog -s n --description 'parameter.  OPTIONS.'
complete -c pg_receivexlog -l directory --description '.'
complete -c pg_receivexlog -l no-loop --description '.'
complete -c pg_receivexlog -l status-interval --description '.'
complete -c pg_receivexlog -l slot --description '.'
complete -c pg_receivexlog -l 'status-interval.' --description '.'
complete -c pg_receivexlog -s v --description '.'
complete -c pg_receivexlog -l verbose --description '.'
complete -c pg_receivexlog -l dbname --description '.'
complete -c pg_receivexlog -l host --description '.'
complete -c pg_receivexlog -l port --description '.'
complete -c pg_receivexlog -l username --description '.'
complete -c pg_receivexlog -s w --description '.'
complete -c pg_receivexlog -l no-password --description '.'
complete -c pg_receivexlog -s W --description '.'
complete -c pg_receivexlog -l password --description '.'
complete -c pg_receivexlog -s V --description '.'
complete -c pg_receivexlog -l version --description '.'
complete -c pg_receivexlog -s '?' --description '.'
complete -c pg_receivexlog -l help --description '.'

