# pg_rewind
# Autogenerated from man page /usr/local/share/man/man1/pg_rewind.1
# using Deroffing man parser
complete -c pg_rewind -s D --description 'This option specifies the target data directory… [See Man Page]'
complete -c pg_rewind -l source-pgdata --description 'Specifies path to the data directory of the sou… [See Man Page]'
complete -c pg_rewind -l source-server --description 'Specifies a libpq connection string to connect … [See Man Page]'
complete -c pg_rewind -o 'n
.br
--dry-run' --description 'Do everything except actually modifying the target directory.'
complete -c pg_rewind -o 'P
.br
--progress' --description 'Enables progress reporting.'
complete -c pg_rewind -l debug --description 'Print verbose debugging output that is mostly u… [See Man Page]'
complete -c pg_rewind -o 'V
.br
--version' --description 'Display version information, then exit.'
complete -c pg_rewind -o '?
.br
--help' --description 'Show help, then exit.'
complete -c pg_rewind -l target-pgdata --description '.'
complete -c pg_rewind -s n --description '.'
complete -c pg_rewind -l dry-run --description '.'
complete -c pg_rewind -s P --description '.'
complete -c pg_rewind -l progress --description '.'
complete -c pg_rewind -s V --description '.'
complete -c pg_rewind -l version --description '.'
complete -c pg_rewind -s '?' --description '.'
complete -c pg_rewind -l help --description '.'

