# pg_test_fsync
# Autogenerated from man page /usr/local/share/man/man1/pg_test_fsync.1
# using Deroffing man parser
complete -c pg_test_fsync -o 'f
.br
--filename' --description 'Specifies the file name to write test data in.'
complete -c pg_test_fsync -o 's
.br
--secs-per-test' --description 'Specifies the number of seconds for each test.'
complete -c pg_test_fsync -o 'V
.br
--version' --description 'Print the pg_test_fsync version and exit.'
complete -c pg_test_fsync -o '?
.br
--help' --description 'Show help about pg_test_fsync command line arguments, and exit.'
complete -c pg_test_fsync -s f --description '.'
complete -c pg_test_fsync -l filename --description '.'
complete -c pg_test_fsync -s s --description '.'
complete -c pg_test_fsync -l secs-per-test --description '.'
complete -c pg_test_fsync -s V --description '.'
complete -c pg_test_fsync -l version --description '.'
complete -c pg_test_fsync -s '?' --description '.'
complete -c pg_test_fsync -l help --description '.'

