# pg_xlogdump
# Autogenerated from man page /usr/local/share/man/man1/pg_xlogdump.1
# using Deroffing man parser
complete -c pg_xlogdump -o 'b
.br
--bkp-details' --description 'Output detailed information about backup blocks.'
complete -c pg_xlogdump -s e --description 'Stop reading at the specified log position, ins… [See Man Page]'
complete -c pg_xlogdump -o 'f
.br
--follow' --description 'After reaching the end of valid WAL, keep polli… [See Man Page]'
complete -c pg_xlogdump -s n --description 'Display the specified number of records, then stop.'
complete -c pg_xlogdump -s p --description 'Directory in which to find log segment files.'
complete -c pg_xlogdump -s r --description 'Only display records generated by the specified… [See Man Page]'
complete -c pg_xlogdump -s s --description 'Log position at which to start reading.'
complete -c pg_xlogdump -s t --description 'Timeline from which to read log records.'
complete -c pg_xlogdump -o 'V
.br
--version' --description 'Print the pg_xlogdump version and exit.'
complete -c pg_xlogdump -s x --description 'Only display records marked with the given transaction ID.'
complete -c pg_xlogdump -o 'z
.br
--stats[' --description 'Display summary statistics (number and size of … [See Man Page]'
complete -c pg_xlogdump -o '?
.br
--help' --description 'Show help about pg_xlogdump command line arguments, and exit.'
complete -c pg_xlogdump -s b --description '.'
complete -c pg_xlogdump -l bkp-details --description '.'
complete -c pg_xlogdump -l end --description '.'
complete -c pg_xlogdump -s f --description '.'
complete -c pg_xlogdump -l follow --description '.'
complete -c pg_xlogdump -l limit --description '.'
complete -c pg_xlogdump -l path --description '.'
complete -c pg_xlogdump -l rmgr --description '.'
complete -c pg_xlogdump -l start --description '.'
complete -c pg_xlogdump -l timelime --description '.'
complete -c pg_xlogdump -s V --description '.'
complete -c pg_xlogdump -l version --description '.'
complete -c pg_xlogdump -l xid --description '.'
complete -c pg_xlogdump -s z --description '.'
complete -c pg_xlogdump -l 'stats[' --description '.'
complete -c pg_xlogdump -s '?' --description '.'
complete -c pg_xlogdump -l help --description '.'

