# ppm2tiff
# Autogenerated from man page /usr/local/share/man/man1/ppm2tiff.1
# using Deroffing man parser
complete -c ppm2tiff -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c ppm2tiff -s r --description 'Write data with a specified number of rows per … [See Man Page]'
complete -c ppm2tiff -s R --description 'Mark the resultant image to have the specified … [See Man Page]'

