# quartz-wm
# Autogenerated from man page /opt/X11/share/man/man1/quartz-wm.1
# using Darwin man parser
complete -c quartz-wm -l prefs-domain --description 'This option can be used to override the domain … [See Man Page]'

