# ras2tiff
# Autogenerated from man page /usr/local/share/man/man1/ras2tiff.1
# using Deroffing man parser
complete -c ras2tiff -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c ras2tiff -s r --description 'Write data with a specified number of rows per … [See Man Page]'

