# rdjpgcom
# Autogenerated from man page /usr/local/share/man/man1/rdjpgcom.1
# using Deroffing man parser
complete -c rdjpgcom -o raw --description 'Normally rdjpgcom escapes non-printable charact… [See Man Page]'
complete -c rdjpgcom -o verbose --description 'Causes rdjpgcom to also display the JPEG image dimensions.'

