# rebase
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/rebase.1
# using Darwin man parser
complete -c rebase -o low_address --description 'Force the base address for the first image to b… [See Man Page]'
complete -c rebase -o high_address --description 'Force the base address for the last image to be… [See Man Page]'
complete -c rebase -o arch --description 'Only rebase the specified architecture.'
complete -c rebase -s v --description 'Verbose.  Print information about rebasing done.'

