# redo_prebinding
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/redo_prebinding.1
# using Deroffing man parser
complete -c redo_prebinding -s c --description 'only check if the file needs to have it\'s prebi… [See Man Page]'
complete -c redo_prebinding -s p --description 'check only for prebound files and return status.'
complete -c redo_prebinding -s d --description 'check only for dynamic shared library files and return status.'
complete -c redo_prebinding -s i --description 'ignore non-prebound files (useful when running … [See Man Page]'
complete -c redo_prebinding -s z --description 'zero out the prebind check sum in the output if it has one.'
complete -c redo_prebinding -s u --description 'unprebind, rather than reprebind (-c, -p, -d, -e ignored).'
complete -c redo_prebinding -s e --description 'replace any dependent library\'s "@executable_pa… [See Man Page]'
complete -c redo_prebinding -o seg_addr_table --description 'The  -seg_addr_table option is used when the in… [See Man Page]'
complete -c redo_prebinding -o seg_addr_table_filename --description 'Use  pathname instead of the install name of th… [See Man Page]'
complete -c redo_prebinding -o seg1addr --description 'Move the input library to base address  address.'
complete -c redo_prebinding -s r --description 'prepend the  rootdir argument to all dependent libraries.'
complete -c redo_prebinding -s o --description 'write the updated file into  output_file rather… [See Man Page]'
complete -c redo_prebinding -s s --description 'write the updated file to standard output DIAGN… [See Man Page]'

