# reindexdb
# Autogenerated from man page /usr/local/share/man/man1/reindexdb.1
# using Deroffing man parser
complete -c reindexdb -o 'a
.br
--all' --description 'Reindex all databases.'
complete -c reindexdb -o 'e
.br
--echo' --description 'Echo the commands that reindexdb generates and … [See Man Page]'
complete -c reindexdb -s i --description 'Recreate index only.'
complete -c reindexdb -o 'q
.br
--quiet' --description 'Do not display progress messages.'
complete -c reindexdb -o 's
.br
--system' --description 'Reindex database\\*(Aqs system catalogs.'
complete -c reindexdb -s S --description 'Reindex schema only.'
complete -c reindexdb -s t --description 'Reindex table only.'
complete -c reindexdb -o 'v
.br
--verbose' --description 'Print detailed information during processing.'
complete -c reindexdb -o 'V
.br
--version' --description 'Print the reindexdb version and exit.'
complete -c reindexdb -o '?
.br
--help' --description 'Show help about reindexdb command line arguments, and exit.'
complete -c reindexdb -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c reindexdb -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c reindexdb -s U --description 'User name to connect as.'
complete -c reindexdb -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c reindexdb -o 'W
.br
--password' --description 'Force reindexdb to prompt for a password before… [See Man Page]'
complete -c reindexdb -l maintenance-db --description 'Specifies the name of the database to connect t… [See Man Page]'
complete -c reindexdb -s a --description '.'
complete -c reindexdb -l all --description '.'
complete -c reindexdb -l 'all)' --description 'PGDATABASE.'
complete -c reindexdb -s e --description '.'
complete -c reindexdb -l echo --description '.'
complete -c reindexdb -l index --description '.'
complete -c reindexdb -s q --description '.'
complete -c reindexdb -l quiet --description '.'
complete -c reindexdb -s s --description '.'
complete -c reindexdb -l system --description '.'
complete -c reindexdb -l schema --description '.'
complete -c reindexdb -l table --description '.'
complete -c reindexdb -s v --description '.'
complete -c reindexdb -l verbose --description '.'
complete -c reindexdb -s V --description '.'
complete -c reindexdb -l version --description '.'
complete -c reindexdb -s '?' --description '.'
complete -c reindexdb -l help --description '.'
complete -c reindexdb -l host --description '.'
complete -c reindexdb -l port --description '.'
complete -c reindexdb -l username --description '.'
complete -c reindexdb -s w --description '.'
complete -c reindexdb -l no-password --description '.'
complete -c reindexdb -s W --description '.'
complete -c reindexdb -l password --description '.'

