# ResMerger
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/ResMerger.1
# using Darwin man parser
complete -c ResMerger -o fileCreator --description 'Sets the HFS creator type of the output file.'
complete -c ResMerger -o fileType --description 'Sets the HFS file type of the output file.'
complete -c ResMerger -o '[a]ppend' --description 'Append to output file, rather than overwriting it.'
complete -c ResMerger -o srcIs --description 'The fork in which to look for resources in the input file(s).'
complete -c ResMerger -o dstIs --description 'The fork in which to write resources in the output file.'
complete -c ResMerger -o skip --description 'Specifies resource type to skip during the resource merge.'
complete -c ResMerger -s o --description 'Specifies the output file.'

