# RezDet
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/RezDet.1
# using Deroffing man parser
complete -c RezDet -o 'b[ig]' --description 'Reads the data for each resource into memory on… [See Man Page]'
complete -c RezDet -o useDF --description 'Reads and writes resource information from the … [See Man Page]'
complete -c RezDet -o noResolve --description 'Prevents the resolution of leaf aliases in the … [See Man Page]'
complete -c RezDet -o 'd[ump]' --description 'Generates the same information as the -s[how] o… [See Man Page]'
complete -c RezDet -o 'l[ist]' --description 'Lists resource types, IDs, names, attributes, a… [See Man Page]'
complete -c RezDet -o 'q[uiet]' --description 'Returns a status code instead of generating error messages.'
complete -c RezDet -o 'r[awdump]' --description 'Generates the same information as the -d[ump] o… [See Man Page]'
complete -c RezDet -o 's[how]' --description 'Writes information about individual resource types.'
complete -c RezDet -s d -s r -s s --description '.'
complete -c RezDet -s 1 --description '.'
complete -c RezDet -o 't[erse]' --description 'Suppresses all messages that do not explicitly describe errors.'

