# RezWack
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/RezWack.1
# using Darwin man parser
complete -c RezWack -s d --description 'Path to the file to use as the data fork of the resulting file.'
complete -c RezWack -o do --description 'Offset from the beginning of the data file from… [See Man Page]'
complete -c RezWack -s r --description 'Path to the file from which to extract resource information.'
complete -c RezWack -o ro --description 'Offset from the beginning of the resource file … [See Man Page]'
complete -c RezWack -s o --description 'Path to the output file to be created.'
complete -c RezWack -s f --description 'Force overwrite of existing output file.'

