# rgb2ycbcr
# Autogenerated from man page /usr/local/share/man/man1/rgb2ycbcr.1
# using Deroffing man parser
complete -c rgb2ycbcr -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c rgb2ycbcr -s h --description 'Set the horizontal sampling dimension to one of… [See Man Page]'
complete -c rgb2ycbcr -s r --description 'Write data with a specified number of rows per … [See Man Page]'
complete -c rgb2ycbcr -s v --description 'options.  Output data are compressed with the.'

