# rpcgen
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/rpcgen.1
# using Darwin man parser
complete -c rpcgen -s a --description 'Generate all the files including sample code fo… [See Man Page]'
complete -c rpcgen -s b --description 'This generates code for the "SunOS 4. 1" style of RPC.'
complete -c rpcgen -s C --description 'Generate code in ANSI C.'
complete -c rpcgen -s c --description 'Compile into XDR routines.'
complete -c rpcgen -s D --description 'Define a symbol name.'
complete -c rpcgen -s h --description 'Compile into C data-definitions (a header file).'
complete -c rpcgen -s K --description 'By default, services created using rpcgen wait … [See Man Page]'
complete -c rpcgen -s L --description 'Server errors will be sent to syslog instead of stderr.'
complete -c rpcgen -s l --description 'Compile into client-side stubs.'
complete -c rpcgen -s m --description 'Compile into server-side stubs, but do not gene… [See Man Page]'
complete -c rpcgen -s N --description 'Use the newstyle of rpcgen.'
complete -c rpcgen -s n --description 'Compile into server-side stubs for the transpor… [See Man Page]'
complete -c rpcgen -s o --description 'Specify the name of the output file.'
complete -c rpcgen -o 'S\\&c' --description 'Generate sample code to show the use of remote … [See Man Page]'
complete -c rpcgen -o 'S\\&s' --description 'Generate skeleton code for the remote procedure… [See Man Page]'
complete -c rpcgen -s s --description 'Compile into server-side stubs for all the tran… [See Man Page]'
complete -c rpcgen -s T --description 'Generate the code to support RPC dispatch tables.'
complete -c rpcgen -s t --description 'Compile into RPC dispatch table.'

