# rsvg-convert
# Autogenerated from man page /usr/local/share/man/man1/rsvg-convert.1
# using Deroffing man parser
complete -c rsvg-convert -s d -l dpi-x --description 'Set the X resolution of the image in pixels per inch.'
complete -c rsvg-convert -s p -l dpi-y --description 'Set the Y resolution of the image in pixels per inch.'
complete -c rsvg-convert -s x -l x-zoom --description 'X Zoom factor, as a percentage.  If unspecified, 1.'
complete -c rsvg-convert -s y -l y-zoom --description 'Y Zoom factor, as a percentage.  If unspecified, 1.'
complete -c rsvg-convert -s z -l -zoom --description 'Zoom factor, as a percentage.  If unspecified, 1.'
complete -c rsvg-convert -s w -l width --description 'Specify how wide you wish the image to be.'
complete -c rsvg-convert -s h -l height --description 'Specify how tall you wish the image to be.'
complete -c rsvg-convert -s f -l format --description 'Specify the output format you wish the image to be saved in.'
complete -c rsvg-convert -s o -l output --description 'Specify the output filename.'
complete -c rsvg-convert -s a -l keep-aspect-ratio --description 'Specify that the aspect ratio is to be preserved.'
complete -c rsvg-convert -s b -l background-color --description 'Specify the background color.'
complete -c rsvg-convert -l base-uri --description 'Specify the base URI for SVG files.'
complete -c rsvg-convert -s v -l version --description 'Display what version of rsvg this is.'

