# sccmap
# Autogenerated from man page /usr/local/share/man/man1/sccmap.1
# using Deroffing man parser
complete -c sccmap -s d --description 'Preserve degenerate components of only one node.'
complete -c sccmap -s s --description 'Do not print the resulting graphs.'
complete -c sccmap -s S --description 'Just print the resulting graphs.  No statistics are printed.'
complete -c sccmap -s o --description 'Prints output to the file output.'
complete -c sccmap -s v --description 'Generate additional statistics.'

