# sdp
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/sdp.1
# using Darwin man parser
complete -c sdp -s f --description 'Specify the output format.'
complete -c sdp -s o --description 'Specify where to write the output.'
complete -c sdp -s A --description 'Output definitions even for items the scripting… [See Man Page]'
complete -c sdp -s V --description 'Specify the minimum compatible system version f… [See Man Page]'
complete -c sdp -s N --description 'Em Bo Objective-C -fh only Bc Ef Specify the base name.'
complete -c sdp -s i --description 'Include the type and class definitions from the specified sdef.'

