# segedit
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/segedit.1
# using Deroffing man parser
complete -c segedit -o extract --description 'Extracts the section specified by the segment n… [See Man Page]'
complete -c segedit -o replace --description 'Will replace the section specified by the segme… [See Man Page]'
complete -c segedit -o segcreate --description 'option.'
complete -c segedit -s l --description 'option to  otool (1).'
complete -c segedit -o output --description 'option must also be specified.'

