# SetFile
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/SetFile.1
# using Darwin man parser
complete -c SetFile -s P --description 'Acts on a symlink file instead on the file the … [See Man Page]'
complete -c SetFile -s a --description 'Sets the file attributes bits where attributes … [See Man Page]'
complete -c SetFile -s c --description 'Specifies the file\'s creator, where creator can… [See Man Page]'
complete -c SetFile -s d --description 'Sets the creation date, where date is a string … [See Man Page]'
complete -c SetFile -s m --description 'Sets the modification date where date is a stri… [See Man Page]'
complete -c SetFile -s t --description 'Sets the file type, where type can be a string … [See Man Page]'

