# sgi2tiff
# Autogenerated from man page /usr/local/share/man/man1/sgi2tiff.1
# using Deroffing man parser
complete -c sgi2tiff -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c sgi2tiff -s p --description 'Explicitly select the planar configuration used… [See Man Page]'
complete -c sgi2tiff -s r --description 'Write data with a specified number of rows per … [See Man Page]'

