# size
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/size.1
# using Deroffing man parser
complete -c size -s m --description 'Print the sizes of the Mach-O segments and sect… [See Man Page]'
complete -c size -s l --description 'When used with the  -m option, also print the a… [See Man Page]'
complete -c size -s x --description 'When used with the  -m option, print the values… [See Man Page]'
complete -c size -o arch --description 'Specifies the architecture, arch_type, of the f… [See Man Page]'

