# smproxy
# Autogenerated from man page /opt/X11/share/man/man1/smproxy.1
# using Deroffing man parser
complete -c smproxy -o clientId --description 'Specifies the session ID used by smproxy in the… [See Man Page]'
complete -c smproxy -o restore --description 'Specifies the file used by smproxy to save stat… [See Man Page]'

