# ssh-copy-id
# Autogenerated from man page /usr/local/share/man/man1/ssh-copy-id.1
# using Darwin man parser
complete -c ssh-copy-id -s i --description 'Use only the key(s) contained in identity_file … [See Man Page]'
complete -c ssh-copy-id -s n --description 'do a dry-run.'
complete -c ssh-copy-id -s h --description 'Print Usage summary.'
complete -c ssh-copy-id -s p --description 'These two options are simply passed through unt… [See Man Page]'

