# startx
# Autogenerated from man page /opt/X11/share/man/man1/startx.1
# using Deroffing man parser
complete -c startx -o auth --description 'argument, from automatically setting up insecur… [See Man Page]'

