# strip
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/strip.1
# using Deroffing man parser
complete -c strip -s u --description 'Save all undefined symbols.'
complete -c strip -s r --description 'Save all symbols referenced dynamically.'
complete -c strip -s s --description 'Save the symbol table entries for the global sy… [See Man Page]'
complete -c strip -s R --description 'Remove the symbol table entries for the global … [See Man Page]'
complete -c strip -s i --description 'Ignore symbols listed in the  -s  filename or  … [See Man Page]'
complete -c strip -s d --description 'Save the debugging symbol table entries for eac… [See Man Page]'
complete -c strip -s A --description 'Save all global absolute symbols except those w… [See Man Page]'
complete -c strip -s n --description 'Save all N_SECT global symbols.'
complete -c strip -s S --description 'Remove the debugging symbol table entries (thos… [See Man Page]'
complete -c strip -s X --description 'Remove the local symbols whose names begin with `L\'.'
complete -c strip -s x --description 'Remove all local symbols (saving only global symbols).'
complete -c strip -s c --description 'Remove the section contents of a dynamic librar… [See Man Page]'
complete -c strip -s o --description 'Write the result into the file  output.'
complete -c strip -o no_uuid --description 'Remove any LC_UUID load commands.'
complete -c strip -s g --description 'option to  cc (1) and other compilers).'
complete -c strip -o arch --description 'Specifies the architecture, arch_type, of the f… [See Man Page]'

