# strings
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/strings.1
# using Deroffing man parser
complete -c strings -s a --description 'This option causes  strings to look for strings… [See Man Page]'
complete -c strings -s o --description 'Preceded each string by its offset in the file (in decimal).'
complete -c strings -s t --description 'Write each string preceded by its byte offset f… [See Man Page]'
complete -c strings -s n --description 'Specify the minimum string length, where the nu… [See Man Page]'
complete -c strings -o arch --description 'Specifies the architecture, arch_type, of the f… [See Man Page]'

