# thumbnail
# Autogenerated from man page /usr/local/share/man/man1/thumbnail.1
# using Deroffing man parser
complete -c thumbnail -s w --description 'Specify the width of thumbnail images in pixels.'
complete -c thumbnail -s h --description 'Specify the height of thumbnail images in pixels.'
complete -c thumbnail -s c --description 'Specify a contrast curve to apply in generating… [See Man Page]'

