# tiffdump
# Autogenerated from man page /usr/local/share/man/man1/tiffdump.1
# using Deroffing man parser
complete -c tiffdump -s h --description 'Force numeric data to be printed in hexadecimal… [See Man Page]'
complete -c tiffdump -s m --description 'Change the number of indirect data items that are printed.'
complete -c tiffdump -s o --description 'Dump the contents of the .'

