# tiffmedian
# Autogenerated from man page /usr/local/share/man/man1/tiffmedian.1
# using Deroffing man parser
complete -c tiffmedian -s c --description 'Specify the compression to use for data written… [See Man Page]'
complete -c tiffmedian -s C --description 'Specify the number of entries to use in the generated colormap.'
complete -c tiffmedian -s f --description 'Apply Floyd-Steinberg dithering before selectin… [See Man Page]'
complete -c tiffmedian -s r --description 'Specify the number of rows (scanlines) in each … [See Man Page]'

