# tiffinfo
# Autogenerated from man page /usr/local/share/man/man1/tiffinfo.1
# using Deroffing man parser
complete -c tiffinfo -s c --description 'Display the colormap and color/gray response cu… [See Man Page]'
complete -c tiffinfo -s D --description 'In addition to displaying the directory tags, r… [See Man Page]'
complete -c tiffinfo -s d --description 'In addition to displaying the directory tags, p… [See Man Page]'
complete -c tiffinfo -s j --description 'Display any \\s-2JPEG\\s0-related tags that are present.'
complete -c tiffinfo -s o --description 'Set the initial .'
complete -c tiffinfo -s s --description 'Display the offsets and byte counts for each da… [See Man Page]'
complete -c tiffinfo -s z --description 'Enable strip chopping when reading image data.'
complete -c tiffinfo -s '#' --description 'Set the initial.'

