# tiffcp
# Autogenerated from man page /usr/local/share/man/man1/tiffcp.1
# using Deroffing man parser
complete -c tiffcp -s a --description 'Append to an existing output file instead of overwriting it.'
complete -c tiffcp -s b --description 'subtract the following monochrome image from al… [See Man Page]'
complete -c tiffcp -s B --description 'Force output to be written with Big-Endian byte order.'
complete -c tiffcp -s C --description 'Suppress the use of ``strip chopping\'\' when rea… [See Man Page]'
complete -c tiffcp -s c --description 'Specify the compression to use for data written… [See Man Page]'
complete -c tiffcp -s f --description 'Specify the bit fill order to use in writing output data.'
complete -c tiffcp -s i --description 'Ignore non-fatal read errors and continue proce… [See Man Page]'
complete -c tiffcp -s l --description 'Specify the length of a tile (in pixels).'
complete -c tiffcp -s L --description 'Force output to be written with Little-Endian byte order.'
complete -c tiffcp -s M --description 'Suppress the use of memory-mapped files when reading images.'
complete -c tiffcp -s o --description 'Set initial directory offset.'
complete -c tiffcp -s p --description 'Specify the planar configuration to use in writ… [See Man Page]'
complete -c tiffcp -s r --description 'Specify the number of rows (scanlines) in each … [See Man Page]'
complete -c tiffcp -s s --description 'Force the output file to be written with data o… [See Man Page]'
complete -c tiffcp -s t --description 'Force the output file to be written with data o… [See Man Page]'
complete -c tiffcp -s w --description 'Specify the width of a tile (in pixels).'
complete -c tiffcp -s x --description 'Force the output file to be written with PAGENU… [See Man Page]'
complete -c tiffcp -s 8 --description 'Write BigTIFF instead of classic TIFF format.'
complete -c tiffcp -s 1 --description 'it will results in infinite number of the rows per strip.'

