# tiffcmp
# Autogenerated from man page /usr/local/share/man/man1/tiffcmp.1
# using Deroffing man parser
complete -c tiffcmp -s l --description 'List each byte of image data that differs between the files.'
complete -c tiffcmp -s z --description 'List specified number of image data bytes that … [See Man Page]'
complete -c tiffcmp -s t --description 'Ignore any differences in directory tags.'

