# tiff2rgba
# Autogenerated from man page /usr/local/share/man/man1/tiff2rgba.1
# using Deroffing man parser
complete -c tiff2rgba -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c tiff2rgba -s r --description 'Write data with a specified number of rows per … [See Man Page]'
complete -c tiff2rgba -s b --description 'Process the image one block (strip/tile) at a t… [See Man Page]'
complete -c tiff2rgba -s n --description 'flag is used, three samples per pixel (red, green, and blue).'

