# tiffdither
# Autogenerated from man page /usr/local/share/man/man1/tiffdither.1
# using Deroffing man parser
complete -c tiffdither -s c --description 'Specify the compression to use for data written… [See Man Page]'
complete -c tiffdither -s f --description 'Specify the bit fill order to use in writing output data.'
complete -c tiffdither -s r --description 'Make each strip have no more than the given number of rows.'
complete -c tiffdither -s t --description 'Set the threshold value for dithering.'

