# tiffsv
# Autogenerated from man page /usr/local/share/man/man1/tiffsv.1
# using Deroffing man parser
complete -c tiffsv -s b --description 'Save the image as a greyscale image as if it we… [See Man Page]'
complete -c tiffsv -s c --description 'Specify the compression to use for data written… [See Man Page]'
complete -c tiffsv -s p --description 'Specify the planar configuration to use in writing image data.'
complete -c tiffsv -s r --description 'Specify the number of rows (scanlines) in each … [See Man Page]'

