# tiff2bw
# Autogenerated from man page /usr/local/share/man/man1/tiff2bw.1
# using Deroffing man parser
complete -c tiff2bw -s c --description 'Specify a compression scheme to use when writin… [See Man Page]'
complete -c tiff2bw -s r --description 'Write data with a specified number of rows per … [See Man Page]'
complete -c tiff2bw -s R --description 'Specify the percentage of the red channel to use (default 28).'
complete -c tiff2bw -s G --description 'Specify the percentage of the green channel to … [See Man Page]'
complete -c tiff2bw -s B --description 'options may be used.  OPTIONS.'

