# unflatten
# Autogenerated from man page /usr/local/share/man/man1/unflatten.1
# using Deroffing man parser
complete -c unflatten -s l --description 'The minimum length of leaf edges is staggered b… [See Man Page]'
complete -c unflatten -s f --description 'Enables the staggering of the -l option to fano… [See Man Page]'
complete -c unflatten -s c --description 'Form disconnected nodes into chains of up to len nodes.'
complete -c unflatten -s o --description 'causes the output to be written to the specifie… [See Man Page]'

