# unifdefall
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/unifdefall.1
# using Darwin man parser
complete -c unifdefall -s D --description 'Specify that a symbol is defined to a given val… [See Man Page]'
complete -c unifdefall -s U --description 'Specify that a symbol is undefined.'
complete -c unifdefall -s b --description 'Replace removed lines with blank lines instead … [See Man Page]'
complete -c unifdefall -s B --description 'Compress blank lines around a deleted section.'
complete -c unifdefall -s c --description 'If the c flag is specified, then the operation … [See Man Page]'
complete -c unifdefall -s d --description 'Turn on printing of debugging messages.  Pp.'
complete -c unifdefall -s e --description 'Because unifdefall processes its input one line… [See Man Page]'
complete -c unifdefall -s K --description 'Always treat the result of && and || operators … [See Man Page]'
complete -c unifdefall -s k --description 'Process #if and #elif lines with constant expressions.'
complete -c unifdefall -s n --description 'Add #line directives to the output following an… [See Man Page]'
complete -c unifdefall -s o --description 'Write output to the file outfile instead of the… [See Man Page]'
complete -c unifdefall -s s --description 'Instead of processing the input file as usual, … [See Man Page]'
complete -c unifdefall -s S --description 'Like the s option, but the nesting depth of eac… [See Man Page]'
complete -c unifdefall -s t --description 'Disables parsing for C comments and line contin… [See Man Page]'
complete -c unifdefall -o iD --description '.'
complete -c unifdefall -o iU --description 'Ignore #ifdef Ns s.'
complete -c unifdefall -s I --description 'Specifies to unifdefall unifdefall an additiona… [See Man Page]'
complete -c unifdefall -s V --description 'Print version details.'

