# unifdef
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/unifdef.1
# using Darwin man parser
complete -c unifdef -s D --description 'Specify that a symbol is defined to a given val… [See Man Page]'
complete -c unifdef -s U --description 'Specify that a symbol is undefined.'
complete -c unifdef -s b --description 'Replace removed lines with blank lines instead … [See Man Page]'
complete -c unifdef -s B --description 'Compress blank lines around a deleted section.'
complete -c unifdef -s c --description 'If the c flag is specified, then the operation … [See Man Page]'
complete -c unifdef -s d --description 'Turn on printing of debugging messages.  Pp.'
complete -c unifdef -s e --description 'Because unifdef processes its input one line at… [See Man Page]'
complete -c unifdef -s K --description 'Always treat the result of && and || operators … [See Man Page]'
complete -c unifdef -s k --description 'Process #if and #elif lines with constant expressions.'
complete -c unifdef -s n --description 'Add #line directives to the output following an… [See Man Page]'
complete -c unifdef -s o --description 'Write output to the file outfile instead of the… [See Man Page]'
complete -c unifdef -s s --description 'Instead of processing the input file as usual, … [See Man Page]'
complete -c unifdef -s S --description 'Like the s option, but the nesting depth of eac… [See Man Page]'
complete -c unifdef -s t --description 'Disables parsing for C comments and line contin… [See Man Page]'
complete -c unifdef -o iD --description '.'
complete -c unifdef -o iU --description 'Ignore #ifdef Ns s.'
complete -c unifdef -s I --description 'Specifies to unifdef unifdefall an additional p… [See Man Page]'
complete -c unifdef -s V --description 'Print version details.'

