# UnRezWack
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/UnRezWack.1
# using Darwin man parser
complete -c UnRezWack -s o --description 'Base path of the output files.'
complete -c UnRezWack -s f --description 'Force overwriting of output files.'

