# uxterm
# Autogenerated from man page /opt/X11/share/man/man1/uxterm.1
# using Deroffing man parser
complete -c uxterm -o class --description 'and.'
complete -c uxterm -o u8 --description 'options should not be specified because they ar… [See Man Page]'

