# vacuumdb
# Autogenerated from man page /usr/local/share/man/man1/vacuumdb.1
# using Deroffing man parser
complete -c vacuumdb -o 'a
.br
--all' --description 'Vacuum all databases.'
complete -c vacuumdb -o 'e
.br
--echo' --description 'Echo the commands that vacuumdb generates and s… [See Man Page]'
complete -c vacuumdb -o 'f
.br
--full' --description 'Perform \\(lqfull\\(rq vacuuming.'
complete -c vacuumdb -o 'F
.br
--freeze' --description 'Aggressively \\(lqfreeze\\(rq tuples.'
complete -c vacuumdb -s j --description 'Execute the vacuum or analyze commands in paral… [See Man Page]'
complete -c vacuumdb -o 'q
.br
--quiet' --description 'Do not display progress messages.'
complete -c vacuumdb -s t --description 'Clean or analyze table only.'
complete -c vacuumdb -o 'v
.br
--verbose' --description 'Print detailed information during processing.'
complete -c vacuumdb -o 'V
.br
--version' --description 'Print the vacuumdb version and exit.'
complete -c vacuumdb -o 'z
.br
--analyze' --description 'Also calculate statistics for use by the optimizer.'
complete -c vacuumdb -o 'Z
.br
--analyze-only' --description 'Only calculate statistics for use by the optimizer (no vacuum).'
complete -c vacuumdb -l analyze-in-stages --description 'Only calculate statistics for use by the optimi… [See Man Page]'
complete -c vacuumdb -o '?
.br
--help' --description 'Show help about vacuumdb command line arguments, and exit.'
complete -c vacuumdb -s h --description 'Specifies the host name of the machine on which… [See Man Page]'
complete -c vacuumdb -s p --description 'Specifies the TCP port or local Unix domain soc… [See Man Page]'
complete -c vacuumdb -s U --description 'User name to connect as.'
complete -c vacuumdb -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c vacuumdb -o 'W
.br
--password' --description 'Force vacuumdb to prompt for a password before … [See Man Page]'
complete -c vacuumdb -l maintenance-db --description 'Specifies the name of the database to connect t… [See Man Page]'
complete -c vacuumdb -s a --description '.'
complete -c vacuumdb -l all --description '.'
complete -c vacuumdb -l 'all)' --description 'PGDATABASE.'
complete -c vacuumdb -s e --description '.'
complete -c vacuumdb -l echo --description '.'
complete -c vacuumdb -s f --description '.'
complete -c vacuumdb -l full --description '.'
complete -c vacuumdb -s F --description '.'
complete -c vacuumdb -l freeze --description '.'
complete -c vacuumdb -l jobs --description '.'
complete -c vacuumdb -s q --description '.'
complete -c vacuumdb -l quiet --description '.'
complete -c vacuumdb -l table --description '.'
complete -c vacuumdb -l analyze --description 'or.'
complete -c vacuumdb -l analyze-only --description 'options.  Multiple tables can be vacuumed by writing multiple.'
complete -c vacuumdb -s v --description '.'
complete -c vacuumdb -l verbose --description '.'
complete -c vacuumdb -s V --description '.'
complete -c vacuumdb -l version --description '.'
complete -c vacuumdb -s z --description '.'
complete -c vacuumdb -s Z --description '.'
complete -c vacuumdb -l 'analyze-only.' --description '.'
complete -c vacuumdb -s '?' --description '.'
complete -c vacuumdb -l help --description '.'
complete -c vacuumdb -l host --description '.'
complete -c vacuumdb -l port --description '.'
complete -c vacuumdb -l username --description '.'
complete -c vacuumdb -s w --description '.'
complete -c vacuumdb -l no-password --description '.'
complete -c vacuumdb -s W --description '.'
complete -c vacuumdb -l password --description '.'

