# vapigen
# Autogenerated from man page /usr/local/share/man/man1/vapigen.1
# using Deroffing man parser
complete -c vapigen -s '?' -l help --description 'Show help option.'
complete -c vapigen -l vapidir --description 'Look for package bindings in DIRECTORY.'
complete -c vapigen -l girdir --description 'Look for GIR bindings in DIRECTORY.'
complete -c vapigen -l metadatadir --description 'Look for GIR . metadata files in DIRECTORY.'
complete -c vapigen -l pkg --description 'Include binding for PACKAGE.'
complete -c vapigen -l library --description 'Specify library name as NAME.'
complete -c vapigen -s d -l directory --description 'Specify output directory as DIRECTORY.'
complete -c vapigen -l version --description 'Display version number and exit.'
complete -c vapigen -s q -l quiet --description 'Do not print messages to the console.'

