# vapigen-0
# Autogenerated from man page /usr/local/share/man/man1/vapigen-0.30.1
# using Deroffing man parser
complete -c vapigen-0 -s '?' -l help --description 'Show help option.'
complete -c vapigen-0 -l vapidir --description 'Look for package bindings in DIRECTORY.'
complete -c vapigen-0 -l girdir --description 'Look for GIR bindings in DIRECTORY.'
complete -c vapigen-0 -l metadatadir --description 'Look for GIR . metadata files in DIRECTORY.'
complete -c vapigen-0 -l pkg --description 'Include binding for PACKAGE.'
complete -c vapigen-0 -l library --description 'Specify library name as NAME.'
complete -c vapigen-0 -s d -l directory --description 'Specify output directory as DIRECTORY.'
complete -c vapigen-0 -l version --description 'Display version number and exit.'
complete -c vapigen-0 -s q -l quiet --description 'Do not print messages to the console.'

