# xbacklight
# Autogenerated from man page /opt/X11/share/man/man1/xbacklight.1
# using Deroffing man parser
complete -c xbacklight -o get --description 'Print out the current backlight brightness of e… [See Man Page]'
complete -c xbacklight -o set --description 'Sets each backlight brightness to the specified level.'
complete -c xbacklight -o inc --description 'Increases brightness by the specified amount.'
complete -c xbacklight -o dec --description 'Decreases brightness by the specified amount.'
complete -c xbacklight -o help --description 'Print out a summary of the usage and exit.'
complete -c xbacklight -o time --description 'Length of time to spend fading the backlight be… [See Man Page]'
complete -c xbacklight -o steps --description 'Number of steps to take while fading.  Default is 20.'

