# xcalc
# Autogenerated from man page /opt/X11/share/man/man1/xcalc.1
# using Deroffing man parser
complete -c xcalc -o stipple --description 'This option indicates that the background of th… [See Man Page]'
complete -c xcalc -o rpn --description 'This option indicates that Reverse Polish Notat… [See Man Page]'

