# xcmsdb
# Autogenerated from man page /opt/X11/share/man/man1/xcmsdb.1
# using Type1
complete -c xcmsdb -o query --description 'This option attempts to read the XDCCC properti… [See Man Page]'
complete -c xcmsdb -o remove --description 'This option attempts to remove the XDCCC proper… [See Man Page]'

