# xcrun
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcrun.1
# using Deroffing man parser
complete -c xcrun -s v -l verbose --description 'Add verbose information on how the tool lookup is performed.'
complete -c xcrun -s n -l no-cache --description 'Don\\(aqt consult the cache when looking up values.'
complete -c xcrun -s k -l kill-cache --description 'Removes the cache.  Causes all values to be re-cached.'
complete -c xcrun -l sdk --description 'Specifies which SDK to search for tools.'
complete -c xcrun -l toolchain --description 'Specifies which toolchain to use to perform the lookup.'
complete -c xcrun -s l -l log --description 'Print the full command line that is invoked. UNINDENT NDENT 0.'
complete -c xcrun -s f -l find --description 'Enable "find" mode, in which the resolved tool … [See Man Page]'
complete -c xcrun -s r -l run --description 'Enable "run" mode, in which the resolved tool p… [See Man Page]'
complete -c xcrun -l show-sdk-path --description 'Print the path to the selected SDK. UNINDENT NDENT 0. 0.'
complete -c xcrun -l show-sdk-version --description 'Print the version number of the selected SDK. UNINDENT NDENT 0.'
complete -c xcrun -l show-sdk-build-version --description 'Print the build version number of the selected SDK.'
complete -c xcrun -l show-sdk-platform-path --description 'Print the path to the platform for the selected SDK.'
complete -c xcrun -l show-sdk-platform-version --description 'Print the version number of the platform for the selected SDK.'

