# xcsbridge
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcsbridge.1
# using Deroffing man parser
complete -c xcsbridge -l format --description 'Specifies the output format for the blueprint, … [See Man Page]'
complete -c xcsbridge -l with-anonymous-urls --description 'If passed, the source control URLs will be stri… [See Man Page]'
complete -c xcsbridge -l with-auth --description 'If passed, the blueprint will contain authentic… [See Man Page]'
complete -c xcsbridge -l no-auth-strategies --description 'If passed, the blueprint will not contain infor… [See Man Page]'
complete -c xcsbridge -l no-required-optional --description 'If passed, the blueprint will not contain infor… [See Man Page]'
complete -c xcsbridge -l no-branches --description 'If passed, the blueprint will not contain branc… [See Man Page]'
complete -c xcsbridge -l no-special-folder-information --description 'If passed, the blueprint will not contain infor… [See Man Page]'
complete -c xcsbridge -l with-favorites --description 'If passed, the blueprint will contain informati… [See Man Page]'
complete -c xcsbridge -l legacy --description 'If passed, all other options (besides --format)… [See Man Page]'

