# xcscontrol
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcscontrol.1
# using Type1
complete -c xcscontrol -s h -l help -l usage --description 'Prints basic usage information.'
complete -c xcscontrol -l version --description 'Displays version information.'
complete -c xcscontrol -l preflight --description 'Preflights the Xcode Server service.'
complete -c xcscontrol -l initialize --description 'Initializes Xcode Server, must be called before… [See Man Page]'
complete -c xcscontrol -l reset --description 'Resets Xcode Server, removing all service data … [See Man Page]'
complete -c xcscontrol -l restart --description 'Restart Xcode Server without removing any service data.'
complete -c xcscontrol -l shutdown --description 'Stops Xcode Server.'

