# xcsgenerator
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcsgenerator.1
# using Darwin man parser
complete -c xcsgenerator -s a --description 'Description of -a flag.'
complete -c xcsgenerator -s b --description 'Description of -b flag \\" Ends the list Pp .'

