# xdm
# Autogenerated from man page /opt/X11/share/man/man1/xdm.1
# using Deroffing man parser
complete -c xdm -o config --description 'Names the configuration file, which specifies r… [See Man Page]'
complete -c xdm -o nodaemon --description 'Specifies ``false\'\' as the value for the DisplayManager.'
complete -c xdm -o debug --description 'Specifies the numeric value for the DisplayManager.'
complete -c xdm -o error --description 'Specifies the value for the DisplayManager.'
complete -c xdm -o resources --description 'Specifies the value for the DisplayManager*resources resource.'
complete -c xdm -o server --description 'Specifies the value for the DisplayManager. servers resource.'
complete -c xdm -o udpPort --description 'Specifies the value for the DisplayManager.'
complete -c xdm -o session --description 'Specifies the value for the DisplayManager*session resource.'
complete -c xdm -o xrm --description 'Allows an arbitrary resource to be specified, a… [See Man Page]'

