# xdpr
# Autogenerated from man page /opt/X11/share/man/man1/xdpr.1
# using Deroffing man parser
complete -c xdpr -o Pprinter --description 'Specifies a printer to send the output to.'
complete -c xdpr -o display --description 'Normally,  xdpr gets the host and display numbe… [See Man Page]'
complete -c xdpr -o device --description 'Specifies the device on which the file will be printed.'
complete -c xdpr -o help --description 'This option displays the list of options known to xdpr.'

