# xdpyinfo
# Autogenerated from man page /opt/X11/share/man/man1/xdpyinfo.1
# using Deroffing man parser
complete -c xdpyinfo -o ext --description 'all, information about all extensions supported… [See Man Page]'

