# xfs
# Autogenerated from man page /opt/X11/share/man/man1/xfs.1
# using Deroffing man parser
complete -c xfs -o config --description 'specifies the configuration file  xfs will use.'
complete -c xfs -o daemon --description 'instructs  xfs to fork and go into the backgrou… [See Man Page]'
complete -c xfs -o droppriv --description 'instructs  xfs to attempt to run as user and gr… [See Man Page]'
complete -c xfs -o inetd --description 'informs  xfs that it is being started by inetd,… [See Man Page]'
complete -c xfs -o ls --description 'specifies a file descriptor which is already se… [See Man Page]'
complete -c xfs -o nodaemon --description 'instructs  xfs not to daemonize (fork and detac… [See Man Page]'
complete -c xfs -o port --description 'specifies the TCP port number on which the serv… [See Man Page]'
complete -c xfs -o user --description 'option is used).'

