# xfsinfo
# Autogenerated from man page /opt/X11/share/man/man1/xfsinfo.1
# using Deroffing man parser
complete -c xfsinfo -o server --description 'This option specifies the X font server to contact.'

