# xinit
# Autogenerated from man page /opt/X11/share/man/man1/xinit.1
# using Deroffing man parser
complete -c xinit -s a -s t --description 'fasthost in which it will run the command cpupi… [See Man Page]'

