# xkbwatch
# Autogenerated from man page /opt/X11/share/man/man1/xkbwatch.1
# using Deroffing man parser
complete -c xkbwatch -o version --description 'This option indicates that the program version … [See Man Page]'

