# xkill
# Autogenerated from man page /opt/X11/share/man/man1/xkill.1
# using Deroffing man parser
complete -c xkill -o display --description 'This option specifies the name of the X server to contact.'
complete -c xkill -o id --description 'This option specifies the X identifier for the … [See Man Page]'
complete -c xkill -o button --description 'This option specifies the number of pointer but… [See Man Page]'
complete -c xkill -o all --description 'This option indicates that all clients with top… [See Man Page]'
complete -c xkill -o frame --description 'This option indicates that xkill should ignore … [See Man Page]'
complete -c xkill -o version --description 'This option makes xkill print its version and e… [See Man Page]'

