# xlogo
# Autogenerated from man page /opt/X11/share/man/man1/xlogo.1
# using Deroffing man parser
complete -c xlogo -o render --description 'This option indicates that the logo should be d… [See Man Page]'
complete -c xlogo -o sharp --description 'If -render is also specified, this forces the e… [See Man Page]'
complete -c xlogo -o shape --description 'This option indicates that the logo window shou… [See Man Page]'

