# xmag
# Autogenerated from man page /opt/X11/share/man/man1/xmag.1
# using Deroffing man parser
complete -c xmag -o source --description 'This option specifies the size and/or location … [See Man Page]'
complete -c xmag -o mag --description 'This option indicates the magnification to be used.'

