# Xnest
# Autogenerated from man page /opt/X11/share/man/man1/Xnest.1
# using Deroffing man parser
complete -c Xnest -o display --description 'This option specifies the display name of the r… [See Man Page]'
complete -c Xnest -o sync --description 'This option tells  Xnest to synchronize its win… [See Man Page]'
complete -c Xnest -o full --description 'This option tells  Xnest to utilize full regene… [See Man Page]'
complete -c Xnest -o class --description 'This option specifies the default visual class … [See Man Page]'
complete -c Xnest -o depth --description 'This option specifies the default visual depth … [See Man Page]'
complete -c Xnest -o sss --description 'This option tells  Xnest to use the software screen saver.'
complete -c Xnest -o geometry --description 'This option specifies the geometry parameters f… [See Man Page]'
complete -c Xnest -o bw --description 'This option specifies the border width of the t… [See Man Page]'
complete -c Xnest -o name --description 'This option specifies the name of the top-level… [See Man Page]'
complete -c Xnest -o scrns --description 'This option specifies the number of screens to … [See Man Page]'
complete -c Xnest -o install --description 'This option tells  Xnest to do its own color ma… [See Man Page]'
complete -c Xnest -o cc --description 'option from the set of standard options except … [See Man Page]'
complete -c Xnest -o parent --description 'This option tells Xnest to use window_id as the… [See Man Page]'

