# xscope
# Autogenerated from man page /opt/X11/share/man/man1/xscope.1
# using Deroffing man parser
complete -c xscope -s i --description 'Specify the port that xscope will use to take r… [See Man Page]'
complete -c xscope -s o --description 'Determines the port that xscope will use to con… [See Man Page]'
complete -c xscope -s h --description 'Determines the host that  xscope will use to fi… [See Man Page]'
complete -c xscope -s d --description 'Defines the display number.'
complete -c xscope -s f --description 'Instead of decoding a live session, reads previ… [See Man Page]'
complete -c xscope -s q --description 'Quiet output mode.'
complete -c xscope -s v --description 'Determines the level of printing which xscope will provide.'
complete -c xscope -s r --description 'Print only raw data without decoding it.'
complete -c xscope -s D --description 'Print debugging information at the specified level.'
complete -c xscope -s I --description 'Enter interactive mode at startup.'
complete -c xscope -s S --description 'Toggle output on or off when SIGUSR1 is received.'
complete -c xscope -s V --description 'Print version information and exit.'
complete -c xscope -s t --description 'Terminate xscope when all clients close.  INTERACTIVE MODE.'
complete -c xscope -o 'o3).' --description 'SEE ALSO X (7), Xsecurity (7), X11 Protocol and… [See Man Page]'

