# xset
# Autogenerated from man page /opt/X11/share/man/man1/xset.1
# using Deroffing man parser
complete -c xset -o display --description 'This option specifies the server to use; see X(7). PP.'
complete -c xset -o dpms --description 'The -dpms option disables DPMS (Energy Star) features.'
complete -c xset -o fp --description 'The -fp and fp- options remove elements from th… [See Man Page]'
complete -c xset -o version --description 'The -version option prints the program version … [See Man Page]'

