# Xvfb
# Autogenerated from man page /opt/X11/share/man/man1/Xvfb.1
# using Deroffing man parser
complete -c Xvfb -o screen --description 'This option creates screen screennum and sets i… [See Man Page]'
complete -c Xvfb -o pixdepths --description 'This option specifies a list of pixmap depths t… [See Man Page]'
complete -c Xvfb -o fbdir --description 'This option specifies the directory in which th… [See Man Page]'
complete -c Xvfb -o shmem --description 'This option specifies that the framebuffer shou… [See Man Page]'
complete -c Xvfb -o linebias --description 'This option specifies how to adjust the pixeliz… [See Man Page]'
complete -c Xvfb -o blackpixel -o whitepixel --description 'These options specify the black and white pixel… [See Man Page]'

