# xvinfo
# Autogenerated from man page /opt/X11/share/man/man1/xvinfo.1
# using Deroffing man parser
complete -c xvinfo -o display --description 'This argument allows you to specify the server … [See Man Page]'
complete -c xvinfo -o short --description 'Output less details, to reduce the amount of text.'
complete -c xvinfo -o version --description 'Output program version, then exit.'

