# xzdec
# Autogenerated from man page /usr/local/share/man/man1/xzdec.1
# using Deroffing man parser
complete -c xzdec -s d -l decompress -l uncompress --description 'Ignored for  xz (1) compatibility.'
complete -c xzdec -s k -l keep --description 'Ignored for  xz (1) compatibility.'
complete -c xzdec -s c -l stdout -l to-stdout --description 'Ignored for  xz (1) compatibility.'
complete -c xzdec -s q -l quiet --description 'Specifying this once does nothing since  xzdec … [See Man Page]'
complete -c xzdec -s Q -l no-warn --description 'Ignored for  xz (1) compatibility.'
complete -c xzdec -s h -l help --description 'Display a help message and exit successfully.'
complete -c xzdec -s V -l version --description 'Display the version number of xzdec and liblzma.  EXIT STATUS.'

