# z
# Autogenerated from man page /usr/local/share/man/man1/z.1
# using Deroffing man parser
complete -c z -s c --description 'restrict matches to subdirectories of the current directory.'
complete -c z -s h --description 'show a brief help message.'
complete -c z -s l --description 'list only.'
complete -c z -s r --description 'match by rank only.'
complete -c z -s t --description 'match by recent access only.'
complete -c z -s x --description 'remove the current directory from the datafile EXAMPLES.'

