---
version: 2
root-markers:
  - .git/
  - tsconfig.json
  - package.json
  - .eslintrc.js
lint-debounce: 1s

tools:
  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  yaml-yamllint: &yaml-yamllint
    lint-command: "yamllint -f parsable -"
    lint-stdin: true

  make-checkmake: &make-checkmake
    lint-command: "checkmake"
    lint-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: "hadolint"
    lint-formats:
      - "%f:%l %m"

  sh-shellcheck: &sh-shellcheck
    lint-command: "shellcheck -f gcc -x"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  sh-shfmt: &sh-shfmt
    format-command: "shfmt -ci -s -bn"
    format-stdin: true

  css-stylelint: &css-stylelint
    lint-command: "yarn stylelint --formatter unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m [%trror]"
      - "%f:%l:%c: %m [%tarning]"

  prettier-format: &prettier-format
    format-command: 'yarn prettier ${INPUT}'
    format-stdin: false

  javascript-eslint: &javascript-eslint
    lint-command: 'yarn eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

languages:
  vim:
    - <<: *vim-vint

  make:
    - <<: *make-checkmake

  yaml:
    - <<: *yaml-yamllint
    - <<: *prettier-format

  dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  css:
    - <<: *css-stylelint
    - <<: *prettier-format

  scss:
    - <<: *css-stylelint
    - <<: *prettier-format

  sass:
    - <<: *css-stylelint
    - <<: *prettier-format

  less:
    - <<: *css-stylelint
    - <<: *prettier-format

  javascript:
    - <<: *javascript-eslint

  javascriptreact:
    - <<: *javascript-eslint

  typescript:
    - <<: *javascript-eslint

  typescriptreact:
    - <<: *javascript-eslint
---
