----------------------------------------------------------------------------------------------------
-- Styles
----------------------------------------------------------------------------------------------------
-- https://github.com/folke/tokyonight.nvim/blob/main/extras/lua/tokyonight_storm.lua
local palette = {
  bg='#24283b',
  bg_dark='#1f2335',
  bg_float='#1f2335',
  bg_highlight='#292e42',
  bg_popup='#1f2335',
  bg_search='#3d59a1',
  bg_sidebar='#1f2335',
  bg_statusline='#1f2335',
  bg_visual='#364a82',
  black='#1d202f',
  blue='#7aa2f7',
  blue0='#3d59a1',
  blue1='#2ac3de',
  blue2='#0db9d7',
  blue5='#89ddff',
  blue6='#b4f9f8',
  blue7='#394b70',
  border='#1d202f',
  border_highlight='#29a4bd',
  comment='#565f89',
  cyan='#7dcfff',
  dark3='#545c7e',
  dark5='#737aa2',
  diff={add='#283b4d', change='#272d43', delete='#3f2d3d', text='#394b70'},
  error='#db4b4b',
  fg='#c0caf5',
  fg_dark='#a9b1d6',
  fg_float='#a9b1d6',
  fg_gutter='#3b4261',
  fg_sidebar='#a9b1d6',
  git={add='#4097a3', change='#506d9b', delete='#c47981', ignore='#545c7e'},
  gitSigns={add='#399a96', change='#6382bd', delete='#c25d64'},
  green='#9ece6a',
  green1='#73daca',
  green2='#41a6b5',
  hint='#1abc9c',
  info='#0db9d7',
  magenta='#bb9af7',
  magenta2='#ff007c',
  none='NONE',
  orange='#ff9e64',
  purple='#9d7cd8',
  red='#f7768e',
  red1='#db4b4b',
  teal='#1abc9c',
  terminal_black='#414868',
  warning='#e0af68',
  yellow='#e0af68'
}

tl.style = {
  border={
    line={'🭽', '▔', '🭾', '▕', '🭿', '▁', '🭼', '▏'},
    rectangle={'┌', '─', '┐', '│', '┘', '─', '└', '│'},
    rounded={'╭', '─', '╮', '│', '╯', '─', '╰', '│'}
  },
  icons={
    separators={vert_bottom_half_block='▄', vert_top_half_block='▀'},
    lsp={
      error='', -- '✗'
      warn='',
      warning='',
      info='', -- 
      hint='' -- ⚑
    },
    git={
      add='', -- '',
      mod='',
      remove='', -- '',
      ignore='',
      rename='',
      diff='',
      repo='',
      logo='',
      branch=''
    },
    documents={file='', files='', folder='', open_folder=''},
    type={array='󰅨', number='', object='', null='󰟢', float='󱂡'},
    misc={
      ellipsis='…',
      up='',
      down='',
      left='',
      right='',
      line='', -- ''
      indent='󰉶',
      tab='⇥',
      bug='', -- 'ﴫ'
      question='',
      clock='',
      lock='',
      circle='',
      project='',
      dashboard='',
      history='',
      comment='',
      robot='󰚩',
      lightbulb='',
      search='',
      code='',
      telescope='',
      gear='',
      package='',
      list='',
      sign_in='',
      check='',
      fire='',
      note='',
      bookmark='',
      pencil='',
      tools='',
      arrow_right='',
      caret_right='',
      chevron_right='',
      chevron_down='',
      double_chevron_right='»',
      table='',
      calendar='',
      block='▌'
    }
  },
  -- LSP Kinds come via the LSP spec
  -- @see: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind
  lsp={
    colors={
      error=palette.error,
      warn=palette.warning,
      hint=palette.hint,
      info=palette.info
    },
    highlights={
      Text='String',
      Method='TSMethod',
      Function='Function',
      Constructor='TSConstructor',
      Field='TSField',
      Variable='TSVariable',
      Class='TSStorageClass',
      Interface='Constant',
      Module='Include',
      Property='TSProperty',
      Unit='Constant',
      Value='Variable',
      Enum='Type',
      Keyword='Keyword',
      File='Directory',
      Reference='PreProc',
      Constant='Constant',
      Struct='Type',
      Snippet='Label',
      Event='Variable',
      Operator='Operator',
      TypeParameter='Type',
      Namespace='TSNamespace',
      Package='Include',
      String='String',
      Number='Number',
      Boolean='Boolean',
      Array='StorageClass',
      Object='Type',
      Key='TSField',
      Null='ErrorMsg',
      EnumMember='TSField'
    },
    kinds={
      codicons={
        Text='',
        Method='',
        Function='',
        Constructor='',
        Field='',
        Variable='',
        Class='',
        Interface='',
        Module='',
        Property='',
        Unit='',
        Value='',
        Enum='',
        Keyword='',
        Snippet='',
        Color='',
        File='',
        Reference='',
        Folder='',
        EnumMember='',
        Constant='',
        Struct='',
        Event='',
        Operator='',
        TypeParameter='',
        Namespace='?',
        Package='?',
        String='?',
        Number='?',
        Boolean='?',
        Array='?',
        Object='?',
        Key='?',
        Null='?'
      },
      nerdfonts={
        Text='',
        Method='',
        Function='',
        Constructor='',
        Field='', -- '',
        Variable='', -- '',
        Class='', -- '',
        Interface='',
        Module='',
        Property='ﰠ',
        Unit='塞',
        Value='',
        Enum='',
        Keyword='', -- '',
        Snippet='', -- '', '',
        Color='',
        File='',
        Reference='', -- '',
        Folder='',
        EnumMember='',
        Constant='', -- '',
        Struct='', -- 'פּ',
        Event='',
        Operator='',
        TypeParameter='',
        Namespace='?',
        Package='?',
        String='?',
        Number='?',
        Boolean='?',
        Array='?',
        Object='?',
        Key='?',
        Null='?'
      }
    }
  },
  palette=palette
}

----------------------------------------------------------------------------------------------------
-- Global style settings
----------------------------------------------------------------------------------------------------
-- Some styles can be tweaked here to apply globally i.e. by setting the current value for that style

-- The current styles for various UI elements
tl.style.current = {
  border=tl.style.border.rounded,
  lsp_icons=tl.style.lsp.kinds.codicons
}

