---
tabs:
  - direction: Horizontal
    parts:
      - direction: Vertical
        split_size:
          Fixed: 1
        run:
          plugin:
            location: "zellij:tab-bar"
        borderless: true
      - direction: Vertical
        split_size:
          Percent: 80
        focus: true
      - direction: Vertical
        split_size:
          Percent: 20
        parts:
          - direction: Vertical
          - direction: Vertical
      - direction: Vertical
        split_size:
          Fixed: 2
        run:
          plugin:
            location: "zellij:status-bar"
        borderless: true
