icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#424242aa"
idle_fg = "#ffffff"
info_bg = "#2196f3aa"
info_fg = "#ffffff"
good_bg = "#8bc34aaa"
good_fg = "#000000aa"
warning_bg = "#ffc107aa"
warning_fg = "#000000aa"
critical_bg = "#f44336aa"
critical_fg = "#ffffff"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000aa"
alternating_tint_fg = "#000000aa"


[[block]]
block = "focused_window"

max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "net"
device = "enp35s0"
interval = 5
graph = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "pacman"

interval = 600

[[block]]
block = "time"
interval = 60
format = "%m-%d (%a) %R"
